// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=wholeheader
// 	 prefix=SHIM_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=SHIM_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=SHIM_HeaderClass
// 	 headerdicomclassprefix=SHIM_Header_BothClass
// 	 headerdumpclassprefix=SHIM_Header_BothClass
// 	 headerinstanceprefix=SHIM_HeaderInstance
// 	 methodnameprefix=SHIM_Method
// 	 methodconstructorargsprefix=SHIM_MethodConstructorArgs
// 	 headerclassparameters=

class SHIM_HeaderClass
{
public:
	SHIM_HeaderClass(istream *ist);

	SHIM_HeaderClass_MAINHDR *SHIM_HeaderInstance_MAINHDR;
};
