// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=dump
// 	 prefix=GE9800_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=GE9800_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=GE9800_HeaderClass
// 	 headerdicomclassprefix=GE9800_Header_BothClass
// 	 headerdumpclassprefix=GE9800_Header_BothClass
// 	 headerinstanceprefix=GE9800_HeaderInstance
// 	 methodnameprefix=GE9800_Method
// 	 methodconstructorargsprefix=GE9800_MethodConstructorArgs
// 	 headerclassparameters=

void 
GE9800_Header_BothClass::DumpCommon(TextOutputStream *log)
{
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 0 << "] "<< "\t Data base membership ID (ASCII '9800') \t <"
		 << String_Use(GE9800_HeaderInstance_GLOBALHDR->unknown6)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 6 << "] "<< "\t Revision Level \t <"
		 << String_Use(GE9800_HeaderInstance_GLOBALHDR->unknown7)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 8 << "] "<< "\t Format code \t <"
		 << String_Use(GE9800_HeaderInstance_GLOBALHDR->unknown8)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 10 << "] "<< "\t User Revision code\t <"
		 << String_Use(GE9800_HeaderInstance_GLOBALHDR->unknown9)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 12 << "] "<< "\t Month of Creation \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown10
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 14 << "] "<< "\t Day of Creation \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown11
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 16 << "] "<< "\t Year of Creation \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown12
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 18 << "] "<< "\t Hour of Creation \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown13
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 20 << "] "<< "\t Minute of Creation \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown14
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 22 << "] "<< "\t Second of Creation \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown15
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 24 << "] "<< "\t Originating Station ID \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown16
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 32 << "] "<< "\t External File Name \t <"
		 << String_Use(GE9800_HeaderInstance_GLOBALHDR->unknown18)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 64 << "] "<< "\t Image Block 0 revision code \t <"
		 << String_Use(GE9800_HeaderInstance_GLOBALHDR->unknown20)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 66 << "] "<< "\t Word ptr to global header (GLOBALHDRPTR)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->GLOBALHDRPTR
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 68 << "] "<< "\t Word ptr to exam header (EXAMHDRPTR)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->EXAMHDRPTR
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 70 << "] "<< "\t Word ptr to image header 1 (IMAGE1HDRPTR)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->IMAGE1HDRPTR
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 72 << "] "<< "\t Word ptr to image header 2 (IMAGE2HDRPTR)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->IMAGE2HDRPTR
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 74 << "] "<< "\t Word ptr to image map (IMAGEMAPPTR)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->IMAGEMAPPTR
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 76 << "] "<< "\t Word ptr to image data (IMAGEDATAPTR)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->IMAGEDATAPTR
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 78 << "] "<< "\t Blocks in global header (GLOBALHDRLNG)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->GLOBALHDRLNG
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 80 << "] "<< "\t Blocks in exam header (EXAMHDRLNG)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->EXAMHDRLNG
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 82 << "] "<< "\t Blocks in image header 1 (IMAGE1HDRLNG)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->IMAGE1HDRLNG
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 84 << "] "<< "\t Blocks in image header 2 (IMAGE2HDRLNG)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->IMAGE2HDRLNG
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 86 << "] "<< "\t Blocks in image map (IMAGEMAPLNG)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->IMAGEMAPLNG
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 88 << "] "<< "\t Blocks in image data (IMAGEDATALNG)\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->IMAGEDATALNG
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 90 << "] "<< "\t max # of images in file \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown36
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 92 << "] "<< "\t 3*16 bits for images \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown37
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 94 << "] "<< "\t Recon done flags \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown38
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 100 << "] "<< "\t Image write locked flags \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown39
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 106 << "] "<< "\t Archive required flags \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown40
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 112 << "] "<< "\t Archive done flags \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown41
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 118 << "] "<< "\t Image removed flags \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown42
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 124 << "] "<< "\t block ptrs to image hdrs \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown43
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 192 << "] "<< "\t should be constant = 1 \t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown44
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_GLOBALHDR_ptr << ":" << 194 << "] "<< "\t should be constant = 512\t <"
		 << GE9800_HeaderInstance_GLOBALHDR->unknown45
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 0 << "] "<< "\t Revision Code \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown49)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 2 << "] "<< "\t CT System number \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown50
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 4 << "] "<< "\t CT Station ID \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown51
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 6 << "] "<< "\t Exam Number (integer)  (StudyNumber)\t <"
		 << GE9800_HeaderInstance_EXAMHDR->StudyNumber
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 8 << "] "<< "\t Exam Number (ascii) \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown53)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 22 << "] "<< "\t Patient ID \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown54)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 34 << "] "<< "\t Patient Name \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown55)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 64 << "] "<< "\t Referring Physician \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown56)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 94 << "] "<< "\t Hospital Name \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown57)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 118 << "] "<< "\t Diagnostician \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown58)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 148 << "] "<< "\t Operator Initials \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown59)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 152 << "] "<< "\t Exam Description \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown60)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 232 << "] "<< "\t # of scout scans \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown64
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 234 << "] "<< "\t # of axial scans \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown65
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 236 << "] "<< "\t # of standard axial scans \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown66
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 238 << "] "<< "\t # of dynamic scans done \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown67
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 240 << "] "<< "\t # of standard target axials \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown68
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 242 << "] "<< "\t # dynamic target axials \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown69
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 244 << "] "<< "\t Exam start Date (M/D/Y)  (EXAMSTARTDATEMM)\t <"
		 << GE9800_HeaderInstance_EXAMHDR->EXAMSTARTDATEMM
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 246 << "] "<< "\t   (EXAMSTARTDATEDD)\t <"
		 << GE9800_HeaderInstance_EXAMHDR->EXAMSTARTDATEDD
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 248 << "] "<< "\t   (EXAMSTARTDATEYY)\t <"
		 << GE9800_HeaderInstance_EXAMHDR->EXAMSTARTDATEYY
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 250 << "] "<< "\t Exam start Time (H/M/S)  (EXAMSTARTTIMEHH)\t <"
		 << GE9800_HeaderInstance_EXAMHDR->EXAMSTARTTIMEHH
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 252 << "] "<< "\t   (EXAMSTARTTIMEMM)\t <"
		 << GE9800_HeaderInstance_EXAMHDR->EXAMSTARTTIMEMM
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 254 << "] "<< "\t  (EXAMSTARTTIMESS)\t <"
		 << GE9800_HeaderInstance_EXAMHDR->EXAMSTARTTIMESS
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 256 << "] "<< "\t Exam end Date (M/D/Y) \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown76
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 258 << "] "<< "\t  \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown77
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 260 << "] "<< "\t  \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown78
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 262 << "] "<< "\t Exam end Time (H/M/S) \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown79
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 264 << "] "<< "\t  \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown80
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 266 << "] "<< "\t \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown81
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 268 << "] "<< "\t Scan Revision Type \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown82
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 270 << "] "<< "\t Trauma Flag (0=n,1=y) \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown83
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 272 << "] "<< "\t CT Detector Type \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown87
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 274 << "] "<< "\t # of Detectors \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown88
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 276 << "] "<< "\t Detector # at theta=0 \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown89
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 280 << "] "<< "\t Detector spacing in mm (fp) \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown90
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 284 << "] "<< "\t Source to detector mm (fp) \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown91
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 288 << "] "<< "\t Source to center mm (fp) \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown92
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 292 << "] "<< "\t Tube type \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown93
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 294 << "] "<< "\t DAS type \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown94)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 298 << "] "<< "\t Das read direction \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown95
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 300 << "] "<< "\t Table firmware revision \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown96)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 304 << "] "<< "\t Drive count \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown97
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 306 << "] "<< "\t Axial trigger rate \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown98
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 308 << "] "<< "\t Scout trigger rate \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown99
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 310 << "] "<< "\t Disk Drive Type \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown100
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 312 << "] "<< "\t Calcheck file ? \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown104
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 314 << "] "<< "\t Header info ok? \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown105
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 316 << "] "<< "\t All prospective recons done? \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown106
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 318 << "] "<< "\t Prospect. & scouts archived? \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown107
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 320 << "] "<< "\t Images archived? \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown108
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 322 << "] "<< "\t Header modified? \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown109
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 324 << "] "<< "\t Validation tape number \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown110
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 326 << "] "<< "\t Engineering release number \t <"
		 << String_Use(GE9800_HeaderInstance_EXAMHDR->unknown111)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 328 << "] "<< "\t temp (was checksum ?)\t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown112
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 330 << "] "<< "\t 9800 Family ID \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown113
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 332 << "] "<< "\t Xenon PRS number \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown114
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 334 << "] "<< "\t Xenon 1st baseline \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown115
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 336 << "] "<< "\t Xenon last baseline \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown116
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 338 << "] "<< "\t Xenon 1st enhanced \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown117
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 340 << "] "<< "\t Xenon last enhanced \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown118
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_EXAMHDR_ptr << ":" << 342 << "] "<< "\t Checksum \t <"
		 << GE9800_HeaderInstance_EXAMHDR->unknown119
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 0 << "] "<< "\t Revision code \t <"
		 << String_Use(GE9800_HeaderInstance_IMAGE1HDR->unknown123)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 2 << "] "<< "\t Station ID \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown124
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 4 << "] "<< "\t Exam Number \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown125
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 6 << "] "<< "\t Exam Number (ascii) \t <"
		 << String_Use(GE9800_HeaderInstance_IMAGE1HDR->unknown126)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 20 << "] "<< "\t Position (study) number \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown127
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 22 << "] "<< "\t Intermediate support pos \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown128
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 24 << "] "<< "\t Group (2=scout,3=std,4=dyn,5=arr)  (GroupType)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->GroupType
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 26 << "] "<< "\t Group Number \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown130
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 28 << "] "<< "\t Group Description \t <"
		 << String_Use(GE9800_HeaderInstance_IMAGE1HDR->unknown131)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 92 << "] "<< "\t Scan Number \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown132
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 94 << "] "<< "\t Image Number  (ImageNumber)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ImageNumber
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 96 << "] "<< "\t Patient Type (2=sm,3=me,4=la)  (PatientType)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->PatientType
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 98 << "] "<< "\t Patient Orientation (1=Head first,2=Feet first)  (PatientOrientation)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->PatientOrientation
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 100 << "] "<< "\t AP Orientation (1=prone,2=supine,3=left lateral decubitus,4=right lateral decubitus)  (APPatientOrientation)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->APPatientOrientation
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 102 << "] "<< "\t Position Reference  (PositionReference)\t <"
		 << String_Use(GE9800_HeaderInstance_IMAGE1HDR->PositionReference)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 108 << "] "<< "\t Contrast Flag (0=n,1=y) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown138
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 110 << "] "<< "\t Contrast Description \t <"
		 << String_Use(GE9800_HeaderInstance_IMAGE1HDR->unknown139)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 174 << "] "<< "\t Bowtie Filter (1=body,2=head,3=a)  (BowtieFilter)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->BowtieFilter
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 176 << "] "<< "\t Aperture (1.5,3,5,10) (fp) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown141
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 180 << "] "<< "\t Generator KVP (80,120,140) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown142
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 182 << "] "<< "\t Tube current (10-360)  (TubeCurrent)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->TubeCurrent
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 184 << "] "<< "\t Gantry Angle  (GantryAngle)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->GantryAngle
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 188 << "] "<< "\t Table Height (mm) (fp) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown145
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 192 << "] "<< "\t Axial Table Location (fp)  (SlicePosition)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->SlicePosition
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 196 << "] "<< "\t Scan time (1.4-9.4) (fp)  (ScanTime)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ScanTime
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 200 << "] "<< "\t Cal phantom size (1=sm,2=md,3=la) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown148
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 202 << "] "<< "\t Cal type (1=air,2=water,3=poly) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown149
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 204 << "] "<< "\t Start of Scan (M/D/Y)  (STARTOFSCANDATEMM)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->STARTOFSCANDATEMM
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 206 << "] "<< "\t   (STARTOFSCANDATEDD)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->STARTOFSCANDATEDD
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 208 << "] "<< "\t   (STARTOFSCANDATEYY)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->STARTOFSCANDATEYY
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 210 << "] "<< "\t Start of Scan (H:M:S)  (STARTOFSCANTIMEHH)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->STARTOFSCANTIMEHH
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 212 << "] "<< "\t   (STARTOFSCANTIMEMM)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->STARTOFSCANTIMEMM
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 214 << "] "<< "\t  (STARTOFSCANTIMESS)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->STARTOFSCANTIMESS
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 216 << "] "<< "\t End of Scan (H:M:S) (ENDOFSCANTIMEHH)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ENDOFSCANTIMEHH
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 218 << "] "<< "\t   (ENDOFSCANTIMEMM)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ENDOFSCANTIMEMM
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 220 << "] "<< "\t  (ENDOFSCANTIMESS)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ENDOFSCANTIMESS
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 222 << "] "<< "\t # of overranged views \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown159
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 224 << "] "<< "\t # overranges \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown160
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 226 << "] "<< "\t Angle of 1st view \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown164
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 228 << "] "<< "\t Scout Scan # use to prescribe \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown165
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 230 << "] "<< "\t Axial type (1=std,2=half,3=over) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown166
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 232 << "] "<< "\t Calcheck image number \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown167
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 234 << "] "<< "\t Prep Delay in sec (fp) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown168
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 238 << "] "<< "\t Mid-scan time in sec (fp) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown169
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 242 << "] "<< "\t Gantry rotation dir (1=cw,2=ccw)  (RotationDirection)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->RotationDirection
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 244 << "] "<< "\t image type (0=no,1=seg,2=tar) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown171
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 246 << "] "<< "\t image size (256/320/512)  (ImageSize)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ImageSize
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 248 << "] "<< "\t table speed (37.5,75. mm/sec) (fp) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown176
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 252 << "] "<< "\t x-ray azimuth angle 0-360)  (TubeAzimuth)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->TubeAzimuth
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 254 << "] "<< "\t scout end loc (mm) (fp)  (ScoutEndLocation)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ScoutEndLocation
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 258 << "] "<< "\t view spacing (mm) (fp)  (ViewSpacing)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ViewSpacing
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 262 << "] "<< "\t # data detectors (wds)/view  (DetectorsPerView)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->DetectorsPerView
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 264 << "] "<< "\t 1st detector # of a view \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown184
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 266 << "] "<< "\t padding/view (to block align) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown185
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 268 << "] "<< "\t view compression factor \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown186
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 270 << "] "<< "\t total input views/scan \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown187
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 272 << "] "<< "\t views/scan (compressed)  (ViewsPerScan)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ViewsPerScan
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 274 << "] "<< "\t views/frame \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown192
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 276 << "] "<< "\t views/superframe \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown193
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 278 << "] "<< "\t frame size in words \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown194
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 280 << "] "<< "\t blocks per frame \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown195
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 282 << "] "<< "\t ref channel rbn pointer \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown196
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 284 << "] "<< "\t drive # of ref channel frame \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown197
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 286 << "] "<< "\t X diam of recon (height) mm (fp)  (XDiameter)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->XDiameter
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 290 << "] "<< "\t Y diam of recon (length) mm (fp)  (YDiameter)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->YDiameter
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 294 << "] "<< "\t Std pixel size for image size = 256  (Pixel256)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->Pixel256
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 298 << "] "<< "\t Std pixel size for image size = 320  (Pixel320)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->Pixel320
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 302 << "] "<< "\t Std pixel size for image size = 512  (Pixel512)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->Pixel512
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 306 << "] "<< "\t Floppy pixel numbers \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown209
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 308 << "] "<< "\t magnification factor (fp)  (MagFactor)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->MagFactor
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 312 << "] "<< "\t image display x center (fp)  (XCenter)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->XCenter
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 316 << "] "<< "\t image display y center (fp)  (YCenter)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->YCenter
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 320 << "] "<< "\t window (-1=default)  (WindowSetting)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->WindowSetting
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 322 << "] "<< "\t level (0=default)  (LevelSetting)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->LevelSetting
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 324 << "] "<< "\t Gamma table (-1=default) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown218
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 326 << "] "<< "\t Hdr modified flag \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown219
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 328 << "] "<< "\t checksum \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown220
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 330 << "] "<< "\t Recon date (M/D/Y)  (RECONDATEMM)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->RECONDATEMM
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 332 << "] "<< "\t   (RECONDATEDD)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->RECONDATEDD
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 334 << "] "<< "\t   (RECONDATEYY)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->RECONDATEYY
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 336 << "] "<< "\t Recon time (H:M:S)  (RECONTIMEHH)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->RECONTIMEHH
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 338 << "] "<< "\t   (RECONTIMEMM)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->RECONTIMEMM
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 340 << "] "<< "\t  (RECONTIMESS)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->RECONTIMESS
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 342 << "] "<< "\t Recon station ID \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown227
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 344 << "] "<< "\t Recon unique number \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown228
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 346 << "] "<< "\t blocks in image (incl headers) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown229
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 348 << "] "<< "\t use image map (1=y,2=n (rect)  (UseImageMap)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->UseImageMap
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 350 << "] "<< "\t line of free text \t <"
		 << String_Use(GE9800_HeaderInstance_IMAGE1HDR->unknown231)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 430 << "] "<< "\t actual image pixel size (mm,fp) (scout), standard pixel size/target factor (recon)  (ReconPixelSize)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ReconPixelSize
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 434 << "] "<< "\t file type (1=prospective,2=scout,3=retrospective,4=segmented,5=screensave,6=plot)  (FileType)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->FileType
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 436 << "] "<< "\t Data range (# bits)  (DataRange)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->DataRange
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 438 << "] "<< "\t 0=std, >0 = segment # \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown238
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 440 << "] "<< "\t back proj. window (0-2) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown239
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 442 << "] "<< "\t preprocess target recon type 0=undefined,1=bone,2=soft tissue,3=quick soft tissue  (PreprocessReconType)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->PreprocessReconType
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 444 << "] "<< "\t actual x_diam recon (hgt) mm-fp  (ReconXDiameter)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ReconXDiameter
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 448 << "] "<< "\t actual y_diam recon (len) mm-fp  (ReconYDiameter)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ReconYDiameter
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 452 << "] "<< "\t x_center of target recon mm-fp  (ReconXCenter)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ReconXCenter
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 456 << "] "<< "\t y-center of target recon mm-fp  (ReconYCenter)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ReconYCenter
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 460 << "] "<< "\t target mag factor  (ReconMagFactor)\t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->ReconMagFactor
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 464 << "] "<< "\t 0 = norm, 1 = halfview \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown249
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 466 << "] "<< "\t sagittal format? (0=n,1=y) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown250
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 468 << "] "<< "\t disk image compressed? \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown251
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 470 << "] "<< "\t scout image orient (0=ap,1=lat) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown252
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 472 << "] "<< "\t archive done flag \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown253
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 474 << "] "<< "\t image use cnt \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown254
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 476 << "] "<< "\t image removed flag \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown255
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 478 << "] "<< "\t image hdr revision code \t <"
		 << String_Use(GE9800_HeaderInstance_IMAGE1HDR->unknown257)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 480 << "] "<< "\t image map type (0=large) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown258
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 482 << "] "<< "\t image origin (1=98,2=88,3=emi) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown259
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 484 << "] "<< "\t image file source format \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown260
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE1HDR_ptr << ":" << 486 << "] "<< "\t flow image flag (0=not) \t <"
		 << GE9800_HeaderInstance_IMAGE1HDR->unknown261
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 0 << "] "<< "\t requesting station id \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown265
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 2 << "] "<< "\t ap1 type \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown266
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 4 << "] "<< "\t # creation failures \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown267
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 6 << "] "<< "\t recon-construction id \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown268
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 8 << "] "<< "\t # ap's in system \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown269
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 10 << "] "<< "\t ap2 type \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown270
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 12 << "] "<< "\t birp type \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown271
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 14 << "] "<< "\t # reference channels/view \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown272
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 16 << "] "<< "\t birp recon symmetry mode \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown273
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 18 << "] "<< "\t # of imhproc != 0 \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown274
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 20 << "] "<< "\t 0=norm, 1=gated \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown275
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 22 << "] "<< "\t 0=normal,1=rubout,2=son of rubout\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown276
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 24 << "] "<< "\t 0=normal,1=oversize,2=fatman,3=both \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown277
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 26 << "] "<< "\t 0=norm,1=iterative \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown278
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 28 << "] "<< "\t fft size (0=nominal) \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown279
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 30 << "] "<< "\t source image type for targ \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown280
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 32 << "] "<< "\t source image number for targ \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown281
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 34 << "] "<< "\t first view number \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown282
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 36 << "] "<< "\t 1=std,2=halfscan,3=overscan \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown283
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 38 << "] "<< "\t 0=std,1=half-detector \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown284
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 40 << "] "<< "\t filename for rubout information\t <"
		 << String_Use(GE9800_HeaderInstance_IMAGE2HDR->unknown285)
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 60 << "] "<< "\t # views in filter region \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown286
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 62 << "] "<< "\t # detectors in filter region \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown287
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 64 << "] "<< "\t filter center wght \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown288
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 68 << "] "<< "\t filter subtraction wght \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown289
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 72 << "] "<< "\t min of cal and windowed data \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown290
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 76 << "] "<< "\t max of cal and windowed data \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown291
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 80 << "] "<< "\t avg of cal and windowed data \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown292
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 84 << "] "<< "\t filter function \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown293
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 86 << "] "<< "\t 8800 Head Scan (0=n,1=y) \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown294
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 88 << "] "<< "\t 8800 Tech factor (0=n,1=y) \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown295
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 90 << "] "<< "\t 8800 SMoothing (0=n,1=y) \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown296
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 92 << "] "<< "\t 8800 Top view # \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown297
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 94 << "] "<< "\t Data Flag (0=rev,1=norm,2=BH, \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown298
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 96 << "] "<< "\t 8800 Dtyp (0=10,1=11,2=11x,3=12) \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown299
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 98 << "] "<< "\t 8800 old contrast flag \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown300
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 100 << "] "<< "\t 8800 0=60Hz, 1 = 50Hz \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown301
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 102 << "] "<< "\t 8800 file complete (0=y) \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown302
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 104 << "] "<< "\t 8800 Bit flags for recond slices \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown303
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 112 << "] "<< "\t 8800 'SS' flag for rev >=EA \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown304
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 114 << "] "<< "\t 8800 Display rev (0=old,1=new) \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown305
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 116 << "] "<< "\t 8800 used by EMI files \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown306
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 118 << "] "<< "\t 8800 Pulse Width Code \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown307
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 120 << "] "<< "\t 8800 Screen save mode \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown308
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 122 << "] "<< "\t 8800 EMI system code \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown309
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 124 << "] "<< "\t 8800 EMI system code \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown310
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 126 << "] "<< "\t 8800 link to raw data run # \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown311
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 128 << "] "<< "\t 8800 3 X-ray counts \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown312
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 130 << "] "<< "\t 8800 link to orig run # \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown313
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 132 << "] "<< "\t 8800 oversize recon flag \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown314
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 134 << "] "<< "\t 8800 Scout DAS speed \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown315
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 136 << "] "<< "\t 8800 Scout C2 table bias \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown316
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 138 << "] "<< "\t 8800 Scout table elevation \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown317
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 140 << "] "<< "\t 8800 Scout Pulse Width cnt \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown318
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 142 << "] "<< "\t 8800 Scout Interp Compr. \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown319
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 146 << "] "<< "\t 8800 Scout Pulse Code Freq \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown320
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 148 << "] "<< "\t # recon checkpoints \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown321
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 150 << "] "<< "\t Percent Xenon used \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown322
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 152 << "] "<< "\t Arterial enhancement val \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown323
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 156 << "] "<< "\t Arterial Rate  constant \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown324
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 160 << "] "<< "\t Xenon Start time (H:M:S) H\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown325
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 162 << "] "<< "\t Xenon Start time (H:M:S) M\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown326
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 164 << "] "<< "\t Xenon Start time (H:M:S) S\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown327
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 166 << "] "<< "\t Hematocrit value \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown328
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 168 << "] "<< "\t PCO2 values 1,2,3 1\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown329
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 170 << "] "<< "\t PCO2 values 1,2,3 2\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown330
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 172 << "] "<< "\t PCO2 values 1,2,3 3\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown331
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 174 << "] "<< "\t Filter used in flow \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown332
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 176 << "] "<< "\t Mask used in flow \t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown333
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 178 << "] "<< "\t Baseline scans 1,2 1\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown334
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 180 << "] "<< "\t Baseline scans 1,2 2\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown335
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 182 << "] "<< "\t enhancement scans 1-6 1\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown336
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 184 << "] "<< "\t enhancement scans 1-6 2\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown337
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 186 << "] "<< "\t enhancement scans 1-6 3\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown338
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 188 << "] "<< "\t enhancement scans 1-6 4\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown339
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 190 << "] "<< "\t enhancement scans 1-6 5\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown340
		 << ">\n";
	(*log)	 << "[" << GE9800_Offset_IMAGE2HDR_ptr << ":" << 192 << "] "<< "\t enhancement scans 1-6 6\t <"
		 << GE9800_HeaderInstance_IMAGE2HDR->unknown341
		 << ">\n";
}

