// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=dicom
// 	 prefix=GE9800_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=GE9800_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=GE9800_HeaderClass
// 	 headerdicomclassprefix=GE9800_Header_BothClass
// 	 headerdumpclassprefix=GE9800_Header_BothClass
// 	 headerinstanceprefix=GE9800_HeaderInstance
// 	 methodnameprefix=GE9800_Method
// 	 methodconstructorargsprefix=GE9800_MethodConstructorArgs
// 	 headerclassparameters=

void 
GE9800_Header_BothClass::ToDicom_Template(AttributeList *list,unsigned imagenumber)
{
	(void)imagenumber;

	(*list)+=new LongStringAttribute(
		TagFromName(SoftwareVersions),
		String_Use(GE9800_HeaderInstance_EXAMHDR->unknown49));

	(*list)+=new ShortStringAttribute(
		TagFromName(StationName),
		GE9800_HeaderInstance_EXAMHDR->unknown51);

	(*list)+=new ShortStringAttribute(
		TagFromName(StudyID),
		GE9800_HeaderInstance_EXAMHDR->StudyNumber);

	(*list)+=new LongStringAttribute(
		TagFromName(PatientID),
		String_Use(GE9800_HeaderInstance_EXAMHDR->unknown54));

	(*list)+=new PersonNameAttribute(
		TagFromName(PatientName),
		String_Use(GE9800_HeaderInstance_EXAMHDR->unknown55));

	(*list)+=new PersonNameAttribute(
		TagFromName(ReferringPhysicianName),
		String_Use(GE9800_HeaderInstance_EXAMHDR->unknown56));

	(*list)+=new LongStringAttribute(
		TagFromName(InstitutionName),
		String_Use(GE9800_HeaderInstance_EXAMHDR->unknown57));

	(*list)+=new PersonNameAttribute(
		TagFromName(PerformingPhysicianName),
		String_Use(GE9800_HeaderInstance_EXAMHDR->unknown58));

	(*list)+=new PersonNameAttribute(
		TagFromName(OperatorsName),
		String_Use(GE9800_HeaderInstance_EXAMHDR->unknown59));

	(*list)+=new LongStringAttribute(
		TagFromName(StudyDescription),
		String_Use(GE9800_HeaderInstance_EXAMHDR->unknown60));

	(*list)+=new DecimalStringAttribute(
		TagFromName(DistanceSourceToDetector),
		GE9800_HeaderInstance_EXAMHDR->unknown91);

	(*list)+=new DecimalStringAttribute(
		TagFromName(DistanceSourceToPatient),
		GE9800_HeaderInstance_EXAMHDR->unknown92);

	(*list)+=new IntegerStringAttribute(
		TagFromName(SeriesNumber),
		GE9800_HeaderInstance_IMAGE1HDR->unknown130);

	(*list)+=new LongStringAttribute(
		TagFromName(SeriesDescription),
		String_Use(GE9800_HeaderInstance_IMAGE1HDR->unknown131));

	(*list)+=new IntegerStringAttribute(
		TagFromName(AcquisitionNumber),
		GE9800_HeaderInstance_IMAGE1HDR->unknown132);

	(*list)+=new IntegerStringAttribute(
		TagFromName(InstanceNumber),
		GE9800_HeaderInstance_IMAGE1HDR->ImageNumber);

	(*list)+=new LongStringAttribute(
		TagFromName(PositionReferenceIndicator),
		String_Use(GE9800_HeaderInstance_IMAGE1HDR->PositionReference));

	(*list)+=new LongStringAttribute(
		TagFromName(ContrastBolusAgent),
		String_Use(GE9800_HeaderInstance_IMAGE1HDR->unknown139));

	(*list)+=new DecimalStringAttribute(
		TagFromName(SliceThickness),
		GE9800_HeaderInstance_IMAGE1HDR->unknown141);

	(*list)+=new DecimalStringAttribute(
		TagFromName(KVP),
		GE9800_HeaderInstance_IMAGE1HDR->unknown142);

	(*list)+=new IntegerStringAttribute(
		TagFromName(XRayTubeCurrent),
		GE9800_HeaderInstance_IMAGE1HDR->TubeCurrent);

	(*list)+=new DecimalStringAttribute(
		TagFromName(GantryDetectorTilt),
		GE9800_HeaderInstance_IMAGE1HDR->GantryAngle);

	(*list)+=new DecimalStringAttribute(
		TagFromName(TableHeight),
		GE9800_HeaderInstance_IMAGE1HDR->unknown145);

	(*list)+=new DecimalStringAttribute(
		TagFromName(SliceLocation),
		GE9800_HeaderInstance_IMAGE1HDR->SlicePosition);

	(*list)+=new UnsignedShortAttribute(
		TagFromName(BitsAllocated),16);

	(*list)+=new UnsignedShortAttribute(
		TagFromName(PixelRepresentation),0);

	(*list)+=new UnsignedShortAttribute(
		TagFromName(SamplesPerPixel),1);

	(*list)+=new CodeStringAttribute(
		TagFromName(PhotometricInterpretation),"MONOCHROME2");

	(*list)+=new DecimalStringAttribute(
		TagFromName(RescaleIntercept),"-1024");

	(*list)+=new DecimalStringAttribute(
		TagFromName(RescaleSlope),"1");

	(*list)+=new LongStringAttribute(
		TagFromName(RescaleType),"HU");

	(*list)+=new ShortStringAttribute(
		TagFromName(AccessionNumber));

	(*list)+=new DateStringAttribute(
		TagFromName(PatientBirthDate));

	(*list)+=new CodeStringAttribute(
		TagFromName(PatientSex));

	(*list)+=new LongStringAttribute(
		TagFromName(Manufacturer),"GE Medical Systems");

	(*list)+=new UIStringAttribute(
		TagFromName(SOPClassUID),"1.2.840.10008.5.1.4.1.1.2");

	(*list)+=new CodeStringAttribute(
		TagFromName(Modality),"CT");

}

