// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=wholeheader
// 	 prefix=GE9800_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=GE9800_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=GE9800_HeaderClass
// 	 headerdicomclassprefix=GE9800_Header_BothClass
// 	 headerdumpclassprefix=GE9800_Header_BothClass
// 	 headerinstanceprefix=GE9800_HeaderInstance
// 	 methodnameprefix=GE9800_Method
// 	 methodconstructorargsprefix=GE9800_MethodConstructorArgs
// 	 headerclassparameters=

class GE9800_HeaderClass
{
public:
	GE9800_HeaderClass(istream *ist);

	GE9800_HeaderClass_GLOBALHDR *GE9800_HeaderInstance_GLOBALHDR;
	GE9800_HeaderClass_EXAMHDR *GE9800_HeaderInstance_EXAMHDR;
	GE9800_HeaderClass_IMAGE1HDR *GE9800_HeaderInstance_IMAGE1HDR;
	GE9800_HeaderClass_IMAGE2HDR *GE9800_HeaderInstance_IMAGE2HDR;
};
