// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=constructheader
// 	 prefix=GE9800_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=GE9800_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=GE9800_HeaderClass
// 	 headerdicomclassprefix=GE9800_Header_BothClass
// 	 headerdumpclassprefix=GE9800_Header_BothClass
// 	 headerinstanceprefix=GE9800_HeaderInstance
// 	 methodnameprefix=GE9800_Method
// 	 methodconstructorargsprefix=GE9800_MethodConstructorArgs
// 	 headerclassparameters=

GE9800_HeaderClass::GE9800_HeaderClass(istream *ist)
{
	GE9800_HeaderInstance_GLOBALHDR = 0;
	GE9800_HeaderInstance_GLOBALHDR = new
		GE9800_HeaderClass_GLOBALHDR(ist,GE9800_Offset_GLOBALHDR_ptr);

	GE9800_HeaderInstance_EXAMHDR = 0;
	GE9800_HeaderInstance_EXAMHDR = new
		GE9800_HeaderClass_EXAMHDR(ist,GE9800_Offset_EXAMHDR_ptr);

	GE9800_HeaderInstance_IMAGE1HDR = 0;
	GE9800_HeaderInstance_IMAGE1HDR = new
		GE9800_HeaderClass_IMAGE1HDR(ist,GE9800_Offset_IMAGE1HDR_ptr);

	GE9800_HeaderInstance_IMAGE2HDR = 0;
	GE9800_HeaderInstance_IMAGE2HDR = new
		GE9800_HeaderClass_IMAGE2HDR(ist,GE9800_Offset_IMAGE2HDR_ptr);

}

