// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=wholeheader
// 	 prefix=PACE_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=PACE_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=PACE_HeaderClass
// 	 headerdicomclassprefix=PACE_Header_BothClass
// 	 headerdumpclassprefix=PACE_Header_BothClass
// 	 headerinstanceprefix=PACE_HeaderInstance
// 	 methodnameprefix=PACE_Method
// 	 methodconstructorargsprefix=PACE_MethodConstructorArgs
// 	 headerclassparameters=

class PACE_HeaderClass
{
public:
	PACE_HeaderClass(istream *ist);

	PACE_HeaderClass_STDHDR *PACE_HeaderInstance_STDHDR;
	PACE_HeaderClass_IMGHDR *PACE_HeaderInstance_IMGHDR;
	PACE_HeaderClass_CTHDR *PACE_HeaderInstance_CTHDR;
	PACE_HeaderClass_MRHDR *PACE_HeaderInstance_MRHDR;
	PACE_HeaderClass_IMGHDR2 *PACE_HeaderInstance_IMGHDR2;
};
