// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=constructheader
// 	 prefix=PACE_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=PACE_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=PACE_HeaderClass
// 	 headerdicomclassprefix=PACE_Header_BothClass
// 	 headerdumpclassprefix=PACE_Header_BothClass
// 	 headerinstanceprefix=PACE_HeaderInstance
// 	 methodnameprefix=PACE_Method
// 	 methodconstructorargsprefix=PACE_MethodConstructorArgs
// 	 headerclassparameters=

PACE_HeaderClass::PACE_HeaderClass(istream *ist)
{
	PACE_HeaderInstance_STDHDR = 0;
	PACE_HeaderInstance_STDHDR = new
		PACE_HeaderClass_STDHDR(ist,PACE_Offset_STDHDR_ptr);

	PACE_HeaderInstance_IMGHDR = 0;
	PACE_HeaderInstance_IMGHDR = new
		PACE_HeaderClass_IMGHDR(ist,PACE_Offset_IMGHDR_ptr);

	PACE_HeaderInstance_CTHDR = 0;
	if (PACE_isct) PACE_HeaderInstance_CTHDR = new
		PACE_HeaderClass_CTHDR(ist,PACE_Offset_CTHDR_ptr);

	PACE_HeaderInstance_MRHDR = 0;
	if (PACE_ismr) PACE_HeaderInstance_MRHDR = new
		PACE_HeaderClass_MRHDR(ist,PACE_Offset_MRHDR_ptr);

	PACE_HeaderInstance_IMGHDR2 = 0;
	PACE_HeaderInstance_IMGHDR2 = new
		PACE_HeaderClass_IMGHDR2(ist,PACE_Offset_IMGHDR2_ptr);

}

