// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=headerpart
// 	 prefix=PACE_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=PACE_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=PACE_HeaderClass
// 	 headerdicomclassprefix=PACE_Header_BothClass
// 	 headerdumpclassprefix=PACE_Header_BothClass
// 	 headerinstanceprefix=PACE_HeaderInstance
// 	 methodnameprefix=PACE_Method
// 	 methodconstructorargsprefix=PACE_MethodConstructorArgs
// 	 headerclassparameters=

class PACE_HeaderClass_STDHDR {
public:
	PACE_HeaderClass_STDHDR(istream *ist,long offset)
		 { ReadProprietaryHeader(ist,offset,sizeof *this,(char *)this); }

	String<4> 	STUDY	; // at 0
	char 		reserved_1	[2]	;
	Uint8_8 	SMODELNO_Mod	; // at 6
	Uint8_8 	SMODELNO_Mac	; // at 7
	Uint16_B 	SMACHINE	; // at 8
	String<5> 	SSTUDYNO	; // at 10
	char 		reserved_2	[1]	;
	String<10> 	SDATE	; // at 16
	String<12> 	STIME	; // at 26
	String<12> 	SPATID	; // at 38
	char 		reserved_3	[4]	;
	String<12> 	SPATNAME	; // at 54
	char 		reserved_4	[14]	;
	String<6> 	SAGE	; // at 80
	String<5> 	SWEIGHT	; // at 86
	char 		reserved_5	[1]	;
	String<2> 	SSEX	; // at 92
	char 		reserved_6	[2]	;
	String<24> 	SMAKER	; // at 96
	String<14> 	SMODELNM	; // at 120
	char 		reserved_7	[10]	;
	String<32> 	SHOSP	; // at 144
	Uint8_8 	SSYSVNO	; // at 176
	Uint8_8 	SSYSRNO	; // at 177
	Uint8_8 	SDATVNO	; // at 178
	Uint8_8 	SDATRNO	; // at 179
	Uint16_B 	SATFRB	; // at 180
	char 		reserved_8	[6]	;
	String<4> 	SENHANCE	; // at 188
	char 		reserved_9	[14]	;
	Pace_Date 	SDATEOD	; // at 206
	Time_Milliseconds_B 	STIMEOD	; // at 210
	Uint32_B 	SSELFOD	; // at 214
	Uint16_B 	SNOBLK	; // at 218
	String<4> 	SIMINFFL_Vol	; // at 220
	Uint16_B 	SIMINFFL_User	; // at 224
	String<8> 	SIMINFFL_Cat	; // at 226
	String<8> 	SIMINFFL_File	; // at 234
	String<2> 	SIMINFFL_Ext	; // at 242
	Uint32_B 	SPOINTIM	; // at 244
	Uint16_B 	SNOSER	; // at 248
	Uint16_B 	SNOACQ	; // at 250
	Uint16_B 	SNOIMG	; // at 252
	Uint16_B 	SNEXTOD	; // at 254
	String<50> 	SDESC1	; // at 256
	String<50> 	SDESC2	; // at 306
	String<50> 	SDESC3	; // at 356
	String<50> 	SDESC4	; // at 406
	String<50> 	SDESC5	; // at 456
};

class PACE_HeaderClass_IMGHDR {
public:
	PACE_HeaderClass_IMGHDR(istream *ist,long offset)
		 { ReadProprietaryHeader(ist,offset,sizeof *this,(char *)this); }

	String<4> 	IMAGE	; // at 0
	Uint16_B 	IBLOCK	; // at 4
	Uint8_8 	IMODELNO_Mod	; // at 6
	Uint8_8 	IMODELNO_Mac	; // at 7
	Uint16_B 	IMACHINE	; // at 8
	String<5> 	ISTUDYNO	; // at 10
	char 		reserved_10	[1]	;
	String<2> 	ISERNO	; // at 16
	String<2> 	IACQNO	; // at 18
	String<2> 	IIMGNO	; // at 20
	char 		reserved_11	[6]	;
	Uint8_8 	ISYSVNO	; // at 28
	Uint8_8 	ISYSRNO	; // at 29
	Uint8_8 	IDATVNO	; // at 30
	Uint8_8 	IDATRNO	; // at 31
	String<10> 	IDATE	; // at 32
	String<12> 	ITIME	; // at 42
	char 		reserved_12	[10]	;
	String<2> 	IHFFIRST	; // at 64
	String<2> 	IPATORI	; // at 66
	String<6> 	IANATOMY	; // at 68
	String<2> 	IAREFHF	; // at 74
	String<2> 	IAREFAP	; // at 76
	String<2> 	IAREFLR	; // at 78
	String<4> 	IPLANE	; // at 80
	IEEE_Float32_B 	ISLPOSHF	; // at 84
	IEEE_Float32_B 	ISLPOSAP	; // at 88
	IEEE_Float32_B 	ISLPOSLR	; // at 92
	IEEE_Float32_B 	ISCENTX	; // at 96
	IEEE_Float32_B 	ISCENTY	; // at 100
	IEEE_Float32_B 	ISCENTZ	; // at 104
	String<4> 	ISFOV	; // at 108
	String<4> 	ISTHICK	; // at 112
	char 		reserved_13	[8]	;
	IEEE_Float32_B 	ITBLPOS	; // at 124
	String<6> 	ISCANSEQ	; // at 128
	char 		reserved_14	[10]	;
	String<5> 	ISCANTM	; // at 144
	char 		reserved_15	[1]	;
	String<4> 	IMTYPE	; // at 150
	char 		reserved_16	[6]	;
	String<4> 	IENHANCE	; // at 160
	String<12> 	ICETIME	; // at 164
	String<4> 	IGENPOW	; // at 176
	String<4> 	ITRIGGER	; // at 180
	char 		reserved_17	[4]	;
	Uint16_B 	IOVERCNT	; // at 188
	Uint16_B 	IZEROCNT	; // at 190
};

class PACE_HeaderClass_CTHDR {
public:
	PACE_HeaderClass_CTHDR(istream *ist,long offset)
		 { ReadProprietaryHeader(ist,offset,sizeof *this,(char *)this); }

	IEEE_Float32_B 	ITBLHGT	; // at 0
	String<3> 	IAZIMUTH	; // at 4
	char 		reserved_18	[1]	;
	String<5> 	IGTILT	; // at 8
	char 		reserved_19	[3]	;
	IEEE_Float32_B 	ISCSTAPS	; // at 16
	IEEE_Float32_B 	ISCENDPS	; // at 20
	String<5> 	IGTILTB	; // at 24
	char 		reserved_20	[3]	;
	String<5> 	IEXPTIME	; // at 32
	char 		reserved_21	[1]	;
	String<3> 	IEXPRATE	; // at 38
	char 		reserved_22	[1]	;
	String<5> 	IEXPOSE	; // at 42
	char 		reserved_23	[1]	;
	String<3> 	IKVP	; // at 48
	char 		reserved_24	[1]	;
	String<2> 	IROTDIR	; // at 52
	String<1> 	IFILTER	; // at 54
	char 		reserved_25	[1]	;
	Pace_Date 	IDATEC	; // at 56
	Time_Milliseconds_B 	ITIMEC	; // at 60
};

class PACE_HeaderClass_MRHDR {
public:
	PACE_HeaderClass_MRHDR(istream *ist,long offset)
		 { ReadProprietaryHeader(ist,offset,sizeof *this,(char *)this); }

	String<5> 	IMRTILT	; // at 0
	char 		reserved_26	[59]	;
	String<2> 	IECHO	; // at 64
	String<2> 	INOOFECH	; // at 66
	String<2> 	ISLICE	; // at 68
	String<2> 	INOOFSL	; // at 70
	String<2> 	INEX	; // at 72
	String<5> 	ITR	; // at 74
	char 		reserved_27	[1]	;
	String<5> 	ITI	; // at 80
	String<5> 	ITE	; // at 85
	char 		reserved_28	[2]	;
	String<4> 	IMATRIXH	; // at 92
	String<4> 	IMATRIXV	; // at 96
	String<4> 	IMATRIXD	; // at 100
	String<1> 	IRCVCOIL_Type	; // at 104
	String<2> 	IRCVCOIL_Num	; // at 105
	char 		reserved_29	[1]	;
	String<1> 	ITRSCOIL_Type	; // at 108
	String<2> 	ITRSCOIL_Num	; // at 109
	char 		reserved_30	[1]	;
	String<4> 	IMAGNET	; // at 112
};

class PACE_HeaderClass_IMGHDR2 {
public:
	PACE_HeaderClass_IMGHDR2(istream *ist,long offset)
		 { ReadProprietaryHeader(ist,offset,sizeof *this,(char *)this); }

	Pace_Date 	ICALDATE	; // at 0
	Time_Milliseconds_B 	ICALTIME	; // at 4
	String<6> 	ICALFOV	; // at 8
	char 		reserved_31	[2]	;
	String<3> 	IIMDIR_NX	; // at 16
	String<3> 	IIMDIR_PY	; // at 19
	String<3> 	IIMDIR_PX	; // at 22
	String<3> 	IIMDIR_NY	; // at 25
	IEEE_Float32_B 	IIMPOSX	; // at 28
	IEEE_Float32_B 	IIMPOSY	; // at 32
	IEEE_Float32_B 	IIMPOSZ	; // at 36
	IEEE_Float32_B 	IIMORIHX	; // at 40
	IEEE_Float32_B 	IIMORIHY	; // at 44
	IEEE_Float32_B 	IIMORIHZ	; // at 48
	IEEE_Float32_B 	IIMORIVX	; // at 52
	IEEE_Float32_B 	IIMORIVY	; // at 56
	IEEE_Float32_B 	IIMORIVZ	; // at 60
	String<1> 	ITCTYPE	; // at 64
	char 		reserved_32	[1]	;
	String<6> 	IRMODE	; // at 66
	IEEE_Float32_B 	IRCENTX	; // at 72
	IEEE_Float32_B 	IRCENTY	; // at 76
	String<4> 	IRFOV	; // at 80
	char 		reserved_33	[12]	;
	Uint16_B 	IXAXIS	; // at 96
	Uint16_B 	IYAXIS	; // at 98
	IEEE_Float32_B 	IPIXSIZE	; // at 100
	Int16_B 	IWINDOWC	; // at 104
	Int16_B 	IWINDOWL	; // at 106
	Uint16_B 	IATTRB	; // at 108
	char 		reserved_34	[2]	;
	IEEE_Float32_B 	IMAGCX	; // at 112
	IEEE_Float32_B 	IMAGCY	; // at 116
	IEEE_Float32_B 	IMAGFACT	; // at 120
	Uint16_B 	ITRANS	; // at 124
	char 		reserved_35	[2]	;
	String<2> 	IREFIMG1_Ser	; // at 128
	char 		reserved_36	[1]	;
	String<2> 	IREFIMG1_Acq	; // at 131
	char 		reserved_37	[1]	;
	String<2> 	IREFIMG1_Img	; // at 134
	String<2> 	IREFIMG2_Ser	; // at 136
	char 		reserved_38	[1]	;
	String<2> 	IREFIMG2_Acq	; // at 139
	char 		reserved_39	[1]	;
	String<2> 	IREFIMG2_Img	; // at 142
	String<2> 	IREFIMG3_Ser	; // at 144
	char 		reserved_40	[1]	;
	String<2> 	IREFIMG3_Acq	; // at 147
	char 		reserved_41	[1]	;
	String<2> 	IREFIMG3_Img	; // at 150
	Uint8_8 	IMASKIMG_Modality	; // at 152
	Uint8_8 	IMASKIMG_Model	; // at 153
	Uint16_B 	IMASKIMG_Serial	; // at 154
	String<3> 	IMASKIMG_Std	; // at 156
	Uint8_8 	IMASKIMG_Ser	; // at 159
	Uint8_8 	IMASKIMG_Acq	; // at 160
	Uint8_8 	IMASKIMG_Img	; // at 161
	char 		reserved_42	[48]	;
	Uint32_B 	ISELFOD	; // at 210
	Uint16_B 	IBITPLNH	; // at 214
	Uint16_B 	IBITPLNV	; // at 216
	Uint32_B 	IPACKIM	; // at 218
	char 		reserved_43	[2]	;
	Uint32_B 	IPACKSZ	; // at 224
	String<4> 	IIMFILE_Vol	; // at 228
	Uint16_B 	IIMFILE_User	; // at 232
	String<8> 	IIMFILE_Cat	; // at 234
	String<8> 	IIMFILE_File	; // at 242
	String<2> 	IIMFILE_Ext	; // at 250
	Uint32_B 	IPOINTIM	; // at 252
	String<16> 	ISRDESC1	; // at 256
	String<14> 	ISRDESC2	; // at 272
	String<12> 	ISRDESC3	; // at 286
	String<10> 	IIMDESC1	; // at 298
	String<8> 	IIMDESC2	; // at 308
	String<7> 	IIMDESC3	; // at 316
	char 		reserved_44	[1]	;
	String<17> 	IEXDESC1	; // at 324
	String<17> 	IEXDESC2	; // at 341
	String<17> 	IEXDESC3	; // at 358
	String<17> 	IEXDESC4	; // at 375
	String<17> 	IEXDESC5	; // at 392
	String<17> 	IEXDESC6	; // at 409
	String<17> 	IEXDESC7	; // at 426
	String<17> 	IEXDESC8	; // at 443
	String<17> 	IEXDESC9	; // at 460
	String<17> 	IEXDESC10	; // at 477
	String<17> 	IEXDESC11	; // at 494
	String<17> 	IEXDESC12	; // at 511
	String<17> 	IEXDESC13	; // at 528
	String<17> 	IEXDESC14	; // at 545
	String<17> 	IEXDESC15	; // at 562
	String<17> 	IEXDESC16	; // at 579
	String<17> 	IEXDESC17	; // at 596
	String<17> 	IEXDESC18	; // at 613
	String<17> 	IEXDESC19	; // at 630
	String<17> 	IEXDESC20	; // at 647
};

