// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=dicom
// 	 prefix=IMTN_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=IMTN_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=IMTN_HeaderClass
// 	 headerdicomclassprefix=IMTN_Header_BothClass
// 	 headerdumpclassprefix=IMTN_Header_BothClass
// 	 headerinstanceprefix=IMTN_HeaderInstance
// 	 methodnameprefix=IMTN_Method
// 	 methodconstructorargsprefix=IMTN_MethodConstructorArgs
// 	 headerclassparameters=

void 
IMTN_Header_BothClass::ToDicom_Template(AttributeList *list,unsigned imagenumber)
{
	(void)imagenumber;

	(*list)+=new LongStringAttribute(
		TagFromName(SoftwareVersions),
		IMTN_HeaderInstance_MAINHDR->VERSION);

	(*list)+=new LongStringAttribute(
		TagFromName(PatientID),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("IPATID"));

	(*list)+=new PersonNameAttribute(
		TagFromName(PatientName),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("IPATNA"));

	(*list)+=new LongStringAttribute(
		TagFromName(StudyDescription),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("ICMNTS"));

	(*list)+=new UnsignedShortAttribute(
		TagFromName(NumberOfDetectors),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedInteger("NDETS"));

	(*list)+=new IntegerStringAttribute(
		TagFromName(ImagesInAcquisition),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedInteger("NSLICE"));

	(*list)+=new LongStringAttribute(
		TagFromName(PositionReferenceIndicator),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("IREF"));

	(*list)+=new LongStringAttribute(
		TagFromName(ContrastBolusAgent),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("ICONTR"));

	(*list)+=new DecimalStringAttribute(
		TagFromName(ContrastBolusVolume),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedFloat("DOSECN"));

	(*list)+=new LongStringAttribute(
		TagFromName(ContrastBolusRoute),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("INJSIT"));

	(*list)+=new PersonNameAttribute(
		TagFromName(ReferringPhysicianName),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("IRPHYS"));

	(*list)+=new PersonNameAttribute(
		TagFromName(PerformingPhysicianName),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("IRADIO"));

	(*list)+=new PersonNameAttribute(
		TagFromName(OperatorsName),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("ITECH"));

	(*list)+=new DecimalStringAttribute(
		TagFromName(SliceThickness),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedInteger("ISTHCK"));

	(*list)+=new LongTextAttribute(
		TagFromName(PatientComments),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("IDIAG"));

	(*list)+=new ShortStringAttribute(
		TagFromName(StationName),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("IHOSP"));

	(*list)+=new ShortStringAttribute(
		TagFromName(ConvolutionKernel),
		IMTN_HeaderInstance_FILEHDR->IMTN_Method_ExtractTaggedString("KERNAM"));

	(*list)+=new DecimalStringAttribute(
		TagFromName(KVP),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedFloat(imagenumber,"HVACT"));

	(*list)+=new IntegerStringAttribute(
		TagFromName(XRayTubeCurrent),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedInteger(imagenumber,"ICURNT"));

	(*list)+=new DecimalStringAttribute(
		TagFromName(ReconstructionDiameter),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedFloat(imagenumber,"PICRAD"));

	(*list)+=new UnsignedShortAttribute(
		TagFromName(Rows),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedInteger(imagenumber,"NROWS"));

	(*list)+=new UnsignedShortAttribute(
		TagFromName(Columns),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedInteger(imagenumber,"NCOLS"));

	(*list)+=new UnspecifiedShortAttribute(
		TagFromName(LargestImagePixelValue),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedFloat(imagenumber,"VALMAX"));

	(*list)+=new UnspecifiedShortAttribute(
		TagFromName(SmallestImagePixelValue),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedFloat(imagenumber,"VALMIN"));

	(*list)+=new DecimalStringAttribute(
		TagFromName(TableHeight),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedInteger(imagenumber,"IHITE"));

	(*list)+=new DecimalStringAttribute(
		TagFromName(GantryDetectorTilt),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedInteger(imagenumber,"ITILT"));

	(*list)+=new DecimalStringAttribute(
		TagFromName(GantryDetectorSlew),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedInteger(imagenumber,"ISLEW"));

	(*list)+=new DecimalStringAttribute(
		TagFromName(TriggerWindow),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedInteger(imagenumber,"ICPHAS"));

	(*list)+=new DecimalStringAttribute(
		TagFromName(HeartRate),
		IMTN_HeaderInstance_SLICEHDR->IMTN_Method_ExtractTaggedFloat(imagenumber,"HRATE"));

	(*list)+=new UnsignedShortAttribute(
		TagFromName(PixelPaddingValue),0);

	(*list)+=new UnsignedShortAttribute(
		TagFromName(BitsAllocated),16);

	(*list)+=new UnsignedShortAttribute(
		TagFromName(BitsStored),16);

	(*list)+=new UnsignedShortAttribute(
		TagFromName(HighBit),15);

	(*list)+=new UnsignedShortAttribute(
		TagFromName(PixelRepresentation),0);

	(*list)+=new UnsignedShortAttribute(
		TagFromName(SamplesPerPixel),1);

	(*list)+=new CodeStringAttribute(
		TagFromName(PhotometricInterpretation),"MONOCHROME2");

	(*list)+=new DecimalStringAttribute(
		TagFromName(RescaleIntercept),"-1000");

	(*list)+=new DecimalStringAttribute(
		TagFromName(RescaleSlope),"1");

	(*list)+=new LongStringAttribute(
		TagFromName(RescaleType),"Hounsfield Units");

	(*list)+=new DecimalStringAttribute(
		TagFromName(WindowCenter),"30");

	(*list)+=new DecimalStringAttribute(
		TagFromName(WindowWidth),"250");

	(*list)+=new LongStringAttribute(
		TagFromName(WindowCenterWidthExplanation),"Soft tissue");

	(*list)+=new ShortStringAttribute(
		TagFromName(AccessionNumber));

	(*list)+=new IntegerStringAttribute(
		TagFromName(SeriesInStudy),"1");

	(*list)+=new IntegerStringAttribute(
		TagFromName(AcquisitionsInStudy),"1");

	(*list)+=new ShortStringAttribute(
		TagFromName(StudyID));

	(*list)+=new IntegerStringAttribute(
		TagFromName(SeriesNumber),"1");

	(*list)+=new IntegerStringAttribute(
		TagFromName(InstanceNumber));

	(*list)+=new LongStringAttribute(
		TagFromName(DeviceSerialNumber));

	(*list)+=new DecimalStringAttribute(
		TagFromName(PatientWeight));

	(*list)+=new CodeStringAttribute(
		TagFromName(PatientSex));

	(*list)+=new LongStringAttribute(
		TagFromName(Manufacturer),"IMATRON");

	(*list)+=new LongStringAttribute(
		TagFromName(ManufacturerModelName),"C-100/150");

	(*list)+=new CodeStringAttribute(
		TagFromName(BodyPartExamined));

	(*list)+=new ShortStringAttribute(
		TagFromName(FilterType));

	(*list)+=new CodeStringAttribute(
		TagFromName(Modality),"CT");

}

