// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=wholeheader
// 	 prefix=SOMP_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=SOMP_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=SOMP_HeaderClass
// 	 headerdicomclassprefix=SOMP_Header_BothClass
// 	 headerdumpclassprefix=SOMP_Header_BothClass
// 	 headerinstanceprefix=SOMP_HeaderInstance
// 	 methodnameprefix=SOMP_Method
// 	 methodconstructorargsprefix=SOMP_MethodConstructorArgs
// 	 headerclassparameters=

class SOMP_HeaderClass
{
public:
	SOMP_HeaderClass(istream *ist);

	SOMP_HeaderClass_BINHDR *SOMP_HeaderInstance_BINHDR;
	SOMP_HeaderClass_TEXTHDR *SOMP_HeaderInstance_TEXTHDR;
};
