// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=dump
// 	 prefix=SOMP_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=SOMP_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=SOMP_HeaderClass
// 	 headerdicomclassprefix=SOMP_Header_BothClass
// 	 headerdumpclassprefix=SOMP_Header_BothClass
// 	 headerinstanceprefix=SOMP_HeaderInstance
// 	 methodnameprefix=SOMP_Method
// 	 methodconstructorargsprefix=SOMP_MethodConstructorArgs
// 	 headerclassparameters=

void 
SOMP_Header_BothClass::DumpCommon(TextOutputStream *log)
{
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 0 << "] "<< "\t (unknown0)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown0
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 2 << "] "<< "\t (unknown2)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown2
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 4 << "] "<< "\t Block size (blksize)\t <"
		 << SOMP_HeaderInstance_BINHDR->blksize
		 << ">\n";
	if (SOMP_HeaderInstance_BINHDR->blksize == 512) (*log) << "\t\t\t 512 = 512 bytes\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 6 << "] "<< "\t Total blocks in file (blkstotal)\t <"
		 << SOMP_HeaderInstance_BINHDR->blkstotal
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 8 << "] "<< "\t (unknown8)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown8
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 10 << "] "<< "\t (unknown10)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown10
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 12 << "] "<< "\t (unknown12)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown12
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 14 << "] "<< "\t (unknown14)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown14
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 16 << "] "<< "\t (unknown16)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown16
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 18 << "] "<< "\t (unknown18)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown18
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 20 << "] "<< "\t (unknown20)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown20
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 22 << "] "<< "\t (unknown22)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown22
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 24 << "] "<< "\t (unknown24)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown24
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 26 << "] "<< "\t (unknown26)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown26
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 28 << "] "<< "\t (unknown28)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown28
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 30 << "] "<< "\t (unknown30)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown30
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 32 << "] "<< "\t (unknown32)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown32
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 34 << "] "<< "\t (unknown34)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown34
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 36 << "] "<< "\t (unknown36)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown36
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 38 << "] "<< "\t (unknown38)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown38
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 40 << "] "<< "\t (unknown40)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown40
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 44 << "] "<< "\t (unknown44)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown44
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 46 << "] "<< "\t (unknown46)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown46
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 48 << "] "<< "\t (unknown48)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown48
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 50 << "] "<< "\t (unknown50)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown50
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 52 << "] "<< "\t (unknown52)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown52
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 54 << "] "<< "\t Blocks in header (blkshdr)\t <"
		 << SOMP_HeaderInstance_BINHDR->blkshdr
		 << ">\n";
	if (SOMP_HeaderInstance_BINHDR->blkshdr == 8) (*log) << "\t\t\t 8 = 4096 byte header\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 56 << "] "<< "\t (unknown56)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown56
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 58 << "] "<< "\t (unknown58)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown58
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 60 << "] "<< "\t (unknown60)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown60
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 62 << "] "<< "\t (unknown62)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown62
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 64 << "] "<< "\t (unknown64)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown64
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 68 << "] "<< "\t (unknown68)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown68
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 72 << "] "<< "\t (unknown72)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown72
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 76 << "] "<< "\t Block offset (from 1) of image pixel data (ptrdata)\t <"
		 << SOMP_HeaderInstance_BINHDR->ptrdata
		 << ">\n";
	if (SOMP_HeaderInstance_BINHDR->ptrdata == 9) (*log) << "\t\t\t 9 = data after 4096 byte header\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 78 << "] "<< "\t Blocks in image pixel data (blksdata)\t <"
		 << SOMP_HeaderInstance_BINHDR->blksdata
		 << ">\n";
	if (SOMP_HeaderInstance_BINHDR->blksdata == 1024) (*log) << "\t\t\t 1024 = length of uncompressed 512 matrix\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 512 << "] "<< "\t (unknown512)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown512
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 516 << "] "<< "\t (version)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->version)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 520 << "] "<< "\t (studydate)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->studydate)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 532 << "] "<< "\t (studytime)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->studytime)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 544 << "] "<< "\t (unknown544)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->unknown544)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 588 << "] "<< "\t (unknown588)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown588
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 592 << "] "<< "\t (unknown592)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown592
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 596 << "] "<< "\t (unknown596)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown596
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 600 << "] "<< "\t (unknown600)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown600
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 604 << "] "<< "\t (unknown604)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown604
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 608 << "] "<< "\t (unknown608)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown608
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 612 << "] "<< "\t (unknown612)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown612
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 616 << "] "<< "\t (unknown616)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown616
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 620 << "] "<< "\t (unknown620)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown620
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 624 << "] "<< "\t (unknown624)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown624
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 628 << "] "<< "\t (unknown628)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown628
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 632 << "] "<< "\t (unknown632)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown632
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 636 << "] "<< "\t (unknown636)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown636
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 640 << "] "<< "\t (unknown640)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown640
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 644 << "] "<< "\t (unknown644)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown644
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 648 << "] "<< "\t (unknown648)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown648
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 652 << "] "<< "\t (unknown652)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown652
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 656 << "] "<< "\t (unknown656)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown656
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 660 << "] "<< "\t (unknown660)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown660
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 664 << "] "<< "\t (model)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->model)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 678 << "] "<< "\t (unknown678)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown678
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 680 << "] "<< "\t (unknown680)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown680
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 684 << "] "<< "\t (unknown684)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown684
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 688 << "] "<< "\t (unknown688)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown688
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 692 << "] "<< "\t (unknown692)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown692
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 696 << "] "<< "\t (uid1)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->uid1)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 708 << "] "<< "\t (uid2)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->uid2)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 772 << "] "<< "\t (unknown772)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown772
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 776 << "] "<< "\t (unknown776)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown776
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 780 << "] "<< "\t (unknown780)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->unknown780)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 852 << "] "<< "\t (unknown852)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->unknown852)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1024 << "] "<< "\t (unknown1024)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1024
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1028 << "] "<< "\t (unknown1028)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1028
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1032 << "] "<< "\t (unknown1032)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1032
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1036 << "] "<< "\t (unknown1036)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1036
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1040 << "] "<< "\t (unknown1040)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1040
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1044 << "] "<< "\t Gantry rotation (?) (rotation)\t <"
		 << SOMP_HeaderInstance_BINHDR->rotation
		 << ">\n";
	if (SOMP_HeaderInstance_BINHDR->rotation == 360) (*log) << "\t\t\t 360 = full\n";
	if (SOMP_HeaderInstance_BINHDR->rotation == 270) (*log) << "\t\t\t 270 = quick\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1048 << "] "<< "\t (description)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->description)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1072 << "] "<< "\t (kv)\t <"
		 << SOMP_HeaderInstance_BINHDR->kv
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1076 << "] "<< "\t (unknown1076)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1076
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1080 << "] "<< "\t (mas)\t <"
		 << SOMP_HeaderInstance_BINHDR->mas
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1084 << "] "<< "\t TI secs (acqtimef)\t <"
		 << SOMP_HeaderInstance_BINHDR->acqtimef
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1088 << "] "<< "\t mm (slthick)\t <"
		 << SOMP_HeaderInstance_BINHDR->slthick
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1092 << "] "<< "\t (unknown1092)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1092
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1096 << "] "<< "\t (unknown1096)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1096
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1100 << "] "<< "\t (unknown1100)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1100
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1108 << "] "<< "\t (unknown1108)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1108
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1112 << "] "<< "\t (unknown1112)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1112
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1116 << "] "<< "\t (unknown1116)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1116
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1120 << "] "<< "\t (unknown1120)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1120
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1124 << "] "<< "\t (unknown1124)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1124
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1128 << "] "<< "\t (unknown1128)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1128
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1132 << "] "<< "\t (unknown1132)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1132
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1136 << "] "<< "\t (unknown1136)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1136
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1140 << "] "<< "\t (unknown1140)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1140
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1148 << "] "<< "\t (unknown1148)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1148
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1152 << "] "<< "\t (unknown1152)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1152
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1156 << "] "<< "\t TI secs (acqtimes)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->acqtimes)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1160 << "] "<< "\t (unknown1160)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1160
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1164 << "] "<< "\t (unknown1164)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1164
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1168 << "] "<< "\t (unknown1168)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1168
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1172 << "] "<< "\t (unknown1172)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1172
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1176 << "] "<< "\t (unknown1176)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1176
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1180 << "] "<< "\t (unknown1180)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1180
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1184 << "] "<< "\t (unknown1184)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1184
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1188 << "] "<< "\t (unknown1188)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1188
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1192 << "] "<< "\t (unknown1192)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1192
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1196 << "] "<< "\t mA (ma)\t <"
		 << SOMP_HeaderInstance_BINHDR->ma
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1200 << "] "<< "\t (unknown1200)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1200
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1204 << "] "<< "\t (unknown1204)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1204
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1208 << "] "<< "\t (unknown1208)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1208
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1212 << "] "<< "\t (unknown1212)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1212
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1280 << "] "<< "\t (unknown1280)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1280
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1284 << "] "<< "\t (unknown1284)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1284
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1288 << "] "<< "\t (unknown1288)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1288
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1292 << "] "<< "\t (unknown1292)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1292
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1296 << "] "<< "\t (unknown1296)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1296
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1300 << "] "<< "\t (unknown1300)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1300
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1302 << "] "<< "\t (unknown1302)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1302
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1304 << "] "<< "\t (unknown1304)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1304
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1308 << "] "<< "\t (unknown1308)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1308
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1312 << "] "<< "\t (unknown1312)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1312
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1316 << "] "<< "\t (unknown1316)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1316
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1320 << "] "<< "\t (unknown1320)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1320
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1324 << "] "<< "\t (unknown1324)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1324
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1328 << "] "<< "\t Matrix size (?) (matrix)\t <"
		 << SOMP_HeaderInstance_BINHDR->matrix
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1332 << "] "<< "\t Zoom factor (?) (zoomfactor)\t <"
		 << SOMP_HeaderInstance_BINHDR->zoomfactor
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1336 << "] "<< "\t (unknown1336)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1336
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1340 << "] "<< "\t (unknown1340)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1340
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1344 << "] "<< "\t (unknown1344)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1344
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1348 << "] "<< "\t (unknown1348)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1348
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1352 << "] "<< "\t (unknown1352)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1352
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1356 << "] "<< "\t (unknown1356)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1356
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1360 << "] "<< "\t (unknown1360)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1360
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1364 << "] "<< "\t (unknown1364)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1364
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1368 << "] "<< "\t (unknown1368)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1368
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1372 << "] "<< "\t (unknown1372)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->unknown1372)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1376 << "] "<< "\t (unknown1376)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1376
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1380 << "] "<< "\t (unknown1380)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1380
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1381 << "] "<< "\t (unknown1381)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->unknown1381)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1384 << "] "<< "\t (unknown1384)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1384
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1388 << "] "<< "\t (unknown1388)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1388
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1392 << "] "<< "\t (unknown1392)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1392
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1396 << "] "<< "\t (unknown1396)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1396
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1400 << "] "<< "\t (unknown1400)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1400
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1404 << "] "<< "\t (unknown1404)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1404
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1408 << "] "<< "\t (unknown1408)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1408
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1412 << "] "<< "\t (unknown1412)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1412
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1416 << "] "<< "\t (unknown1416)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1416
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1420 << "] "<< "\t (unknown1420)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1420
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1424 << "] "<< "\t (unknown1424)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1424
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1428 << "] "<< "\t (unknown1428)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1428
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1540 << "] "<< "\t (unknown1540)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1540
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1544 << "] "<< "\t TP mm (tableposn)\t <"
		 << SOMP_HeaderInstance_BINHDR->tableposn
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1548 << "] "<< "\t Table height mm ? (tableheight)\t <"
		 << SOMP_HeaderInstance_BINHDR->tableheight
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1552 << "] "<< "\t (unknown1552)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1552
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1556 << "] "<< "\t (unknown1556)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1556
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1560 << "] "<< "\t Scan number (scannumber)\t <"
		 << SOMP_HeaderInstance_BINHDR->scannumber
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1564 << "] "<< "\t (scandate)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->scandate)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1576 << "] "<< "\t (scantime)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->scantime)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1588 << "] "<< "\t (unknown1588)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->unknown1588)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1612 << "] "<< "\t (unknown1612)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1612
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1616 << "] "<< "\t (unknown1616)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1616
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1620 << "] "<< "\t (unknown1620)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1620
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1664 << "] "<< "\t (unknown1664)\t <"
		 << String_Use(SOMP_HeaderInstance_BINHDR->unknown1664)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1704 << "] "<< "\t (unknown1704)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1704
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1708 << "] "<< "\t (unknown1708)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1708
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1718 << "] "<< "\t (unknown1718)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1718
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1720 << "] "<< "\t (unknown1720)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1720
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1722 << "] "<< "\t (unknown1722)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1722
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1724 << "] "<< "\t (unknown1724)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1724
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1726 << "] "<< "\t (unknown1726)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1726
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1728 << "] "<< "\t (unknown1728)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1728
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1792 << "] "<< "\t (unknown1792)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1792
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1794 << "] "<< "\t (unknown1794)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1794
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1796 << "] "<< "\t (unknown1796)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1796
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1798 << "] "<< "\t (unknown1798)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1798
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1800 << "] "<< "\t (unknown1800)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1800
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1802 << "] "<< "\t (unknown1802)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1802
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1804 << "] "<< "\t (unknown1804)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1804
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1808 << "] "<< "\t (unknown1808)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1808
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1810 << "] "<< "\t (unknown1810)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1810
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1812 << "] "<< "\t (unknown1812)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1812
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1814 << "] "<< "\t (unknown1814)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1814
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1816 << "] "<< "\t (unknown1816)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1816
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1820 << "] "<< "\t (unknown1820)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1820
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1824 << "] "<< "\t (unknown1824)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1824
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1826 << "] "<< "\t (unknown1826)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1826
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1828 << "] "<< "\t (unknown1828)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1828
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1830 << "] "<< "\t (unknown1830)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1830
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1832 << "] "<< "\t (unknown1832)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1832
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1834 << "] "<< "\t (unknown1834)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1834
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_BINHDR_ptr << ":" << 1836 << "] "<< "\t (unknown1836)\t <"
		 << SOMP_HeaderInstance_BINHDR->unknown1836
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 4 << "] "<< "\t (tproduct)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tproduct)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 25 << "] "<< "\t (tversion)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tversion)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 30 << "] "<< "\t (thospital)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->thospital)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 60 << "] "<< "\t (ttime)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->ttime)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 72 << "] "<< "\t (tsliceno)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tsliceno)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 84 << "] "<< "\t (ttableposnf)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->ttableposnf)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->ttableposnf),"TP",2)==0) (*log) << "\t\t 'TP' = Table position mm\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 86 << "] "<< "\t (ttableposn)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->ttableposn)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 96 << "] "<< "\t (tpatname)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tpatname)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 120 << "] "<< "\t (tpatid)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tpatid)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 133 << "] "<< "\t (tdate)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tdate)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 145 << "] "<< "\t (tacqtimesf)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tacqtimesf)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tacqtimesf),"TI",2)==0) (*log) << "\t\t 'TI' = Acquisition time secs\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 147 << "] "<< "\t (tacqtimes)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tacqtimes)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 157 << "] "<< "\t (tmasf)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tmasf)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tmasf),"mAs",3)==0) (*log) << "\t\t 'mAs' = Exposure mAs\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 160 << "] "<< "\t (tmas)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tmas)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 169 << "] "<< "\t (tkvf)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tkvf)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tkvf),"kV",2)==0) (*log) << "\t\t 'kV' = Tube voltage kV\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 171 << "] "<< "\t (tkv)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tkv)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 181 << "] "<< "\t (tslf)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tslf)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tslf),"SL",2)==0) (*log) << "\t\t 'SL' = Slice thickness mm\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 183 << "] "<< "\t (tsl)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tsl)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 193 << "] "<< "\t (tgtf)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tgtf)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tgtf),"GT",2)==0) (*log) << "\t\t 'GT' = Gantry Tilt degrees\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 195 << "] "<< "\t (tgt)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tgt)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 205 << "] "<< "\t (tzof)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tzof)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tzof),"ZO",2)==0) (*log) << "\t\t 'ZO' = Zoom factor\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 207 << "] "<< "\t (tzo)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tzo)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 217 << "] "<< "\t (tcef)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tcef)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tcef),"CE",2)==0) (*log) << "\t\t 'CE' = Zoom center\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 219 << "] "<< "\t (tcex)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tcex)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 231 << "] "<< "\t (tcey)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tcey)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 241 << "] "<< "\t (tmaf)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tmaf)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tmaf),"CE",2)==0) (*log) << "\t\t 'CE' = Tube current mA\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 243 << "] "<< "\t (tma)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tma)
		 << ">\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 253 << "] "<< "\t (tlabelright)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tlabelright)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabelright),"LEFT",10)==0) (*log) << "\t\t 'LEFT' = left\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabelright),"RIGHT",10)==0) (*log) << "\t\t 'RIGHT' = Right\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabelright),"ANTERIOR",10)==0) (*log) << "\t\t 'ANTERIOR' = Anterior\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabelright),"POSTERIOR",10)==0) (*log) << "\t\t 'POSTERIOR' = Posterior\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabelright),"HEAD",10)==0) (*log) << "\t\t 'HEAD' = Head\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabelright),"FEET",10)==0) (*log) << "\t\t 'FEET' = Feet\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 263 << "] "<< "\t (tlabeltop)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tlabeltop)
		 << ">\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabeltop),"LEFT",10)==0) (*log) << "\t\t 'LEFT' = left\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabeltop),"RIGHT",10)==0) (*log) << "\t\t 'RIGHT' = Right\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabeltop),"ANTERIOR",10)==0) (*log) << "\t\t 'ANTERIOR' = Anterior\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabeltop),"POSTERIOR",10)==0) (*log) << "\t\t 'POSTERIOR' = Posterior\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabeltop),"HEAD",10)==0) (*log) << "\t\t 'HEAD' = Head\n";
	if (strncmp(String_Use(SOMP_HeaderInstance_TEXTHDR->tlabeltop),"FEET",10)==0) (*log) << "\t\t 'FEET' = Feet\n";
	(*log)	 << "[" << SOMP_Offset_TEXTHDR_ptr << ":" << 273 << "] "<< "\t (tcomment)\t <"
		 << String_Use(SOMP_HeaderInstance_TEXTHDR->tcomment)
		 << ">\n";
}

