// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=constructheader
// 	 prefix=GAW_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=GAW_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=GAW_HeaderClass
// 	 headerdicomclassprefix=GAW_Header_BothClass
// 	 headerdumpclassprefix=GAW_Header_BothClass
// 	 headerinstanceprefix=GAW_HeaderInstance
// 	 methodnameprefix=GAW_Method
// 	 methodconstructorargsprefix=GAW_MethodConstructorArgs
// 	 headerclassparameters=,GAW_FileStructureInformation &fileinfo

GAW_HeaderClass::GAW_HeaderClass(istream *ist,GAW_FileStructureInformation &fileinfo)
{
	GAW_HeaderInstance_FILEHDR = 0;
	GAW_HeaderInstance_FILEHDR = new
		GAW_HeaderClass_FILEHDR(ist,GAW_Offset_FILEHDR_ptr);

	GAW_HeaderInstance_UIDHDR = 0;
	if (GAW_hasuid) GAW_HeaderInstance_UIDHDR = new
		GAW_HeaderClass_UIDHDR(ist,GAW_Offset_UIDHDR_ptr);

	GAW_HeaderInstance_HISTOHDR = 0;
	if (GAW_hashisto) GAW_HeaderInstance_HISTOHDR = new
		GAW_HeaderClass_HISTOHDR(ist,GAW_Offset_HISTOHDR_ptr);

	GAW_HeaderInstance_SUITEHDR = 0;
	GAW_HeaderInstance_SUITEHDR = new
		GAW_HeaderClass_SUITEHDR(ist,GAW_Offset_SUITEHDR_ptr);

	GAW_HeaderInstance_EXAMHDR = 0;
	GAW_HeaderInstance_EXAMHDR = new
		GAW_HeaderClass_EXAMHDR(ist,GAW_Offset_EXAMHDR_ptr);

	GAW_HeaderInstance_SERIESHDR = 0;
	GAW_HeaderInstance_SERIESHDR = new
		GAW_HeaderClass_SERIESHDR(ist,GAW_Offset_SERIESHDR_ptr);

	GAW_HeaderInstance_CTHDR = 0;
	if (GAW_isct) GAW_HeaderInstance_CTHDR = new
		GAW_HeaderClass_CTHDR(ist,GAW_Offset_CTHDR_ptr);

	GAW_HeaderInstance_MRHDR = 0;
	if (GAW_ismr) GAW_HeaderInstance_MRHDR = new
		GAW_HeaderClass_MRHDR(ist,GAW_Offset_MRHDR_ptr);

}

