// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=wholeheader
// 	 prefix=GAW_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=GAW_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=GAW_HeaderClass
// 	 headerdicomclassprefix=GAW_Header_BothClass
// 	 headerdumpclassprefix=GAW_Header_BothClass
// 	 headerinstanceprefix=GAW_HeaderInstance
// 	 methodnameprefix=GAW_Method
// 	 methodconstructorargsprefix=GAW_MethodConstructorArgs
// 	 headerclassparameters=,GAW_FileStructureInformation &fileinfo

class GAW_HeaderClass
{
public:
	GAW_HeaderClass(istream *ist,GAW_FileStructureInformation &fileinfo);

	GAW_HeaderClass_FILEHDR *GAW_HeaderInstance_FILEHDR;
	GAW_HeaderClass_UIDHDR *GAW_HeaderInstance_UIDHDR;
	GAW_HeaderClass_HISTOHDR *GAW_HeaderInstance_HISTOHDR;
	GAW_HeaderClass_SUITEHDR *GAW_HeaderInstance_SUITEHDR;
	GAW_HeaderClass_EXAMHDR *GAW_HeaderInstance_EXAMHDR;
	GAW_HeaderClass_SERIESHDR *GAW_HeaderInstance_SERIESHDR;
	GAW_HeaderClass_CTHDR *GAW_HeaderInstance_CTHDR;
	GAW_HeaderClass_MRHDR *GAW_HeaderInstance_MRHDR;
};
