// Automatically generated - EDITS WILL BE LOST

// Generated by support/setplatform

#include "platform.h"

const char* dicom3tools_platform_string = "Linux runnervmymu0l 6.11.0-1018-azure #18~24.04.1-Ubuntu SMP Sat Jun 28 04:46:03 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux";
