// Automatically generated from template - EDITS WILL BE LOST

// Generated by transyn.awk with options extern transynu

#ifndef __Header_transynu__
#define __Header_transynu__

extern const char *ImplicitVRLittleEndianTransferSyntaxUID;
extern const char *DefaultTransferSyntaxUID;
extern const char *CommandTransferSyntaxUID;
extern const char *Papyrus3TransferSyntaxUID;
extern const char *ExplicitVRLittleEndianTransferSyntaxUID;
extern const char *MetaInformationTransferSyntaxUID;
extern const char *ExplicitVRBigEndianTransferSyntaxUID;
extern const char *JPEGProcess1TransferSyntaxUID;
extern const char *JPEGProcess2_4TransferSyntaxUID;
extern const char *JPEGProcess3_5TransferSyntaxUID;
extern const char *JPEGProcess6_8TransferSyntaxUID;
extern const char *JPEGProcess7_9TransferSyntaxUID;
extern const char *JPEGProcess10_12TransferSyntaxUID;
extern const char *JPEGProcess11_13TransferSyntaxUID;
extern const char *JPEGProcess14TransferSyntaxUID;
extern const char *JPEGProcess15TransferSyntaxUID;
extern const char *JPEGProcess16_18TransferSyntaxUID;
extern const char *JPEGProcess17_19TransferSyntaxUID;
extern const char *JPEGProcess20_22TransferSyntaxUID;
extern const char *JPEGProcess21_23TransferSyntaxUID;
extern const char *JPEGProcess24_26TransferSyntaxUID;
extern const char *JPEGProcess25_27TransferSyntaxUID;
extern const char *JPEGProcess28TransferSyntaxUID;
extern const char *JPEGProcess29TransferSyntaxUID;
extern const char *JPEGProcess14SV1TransferSyntaxUID;
extern const char *JPEGLSLosslessTransferSyntaxUID;
extern const char *JPEGLSNearLosslessTransferSyntaxUID;
extern const char *JPEG2000LosslessTransferSyntaxUID;
extern const char *JPEG2000TransferSyntaxUID;
extern const char *JPEGXLLosslessTransferSyntaxUID;
extern const char *JPEGXLRecompressionTransferSyntaxUID;
extern const char *JPEGXLTransferSyntaxUID;
extern const char *HTJ2KLosslessTransferSyntaxUID;
extern const char *HTJ2KLosslessRCPLTransferSyntaxUID;
extern const char *HTJ2KTransferSyntaxUID;
extern const char *MPEG2MPMLTransferSyntaxUID;
extern const char *MPEG2MPHLTransferSyntaxUID;
extern const char *MPEG4HP41TransferSyntaxUID;
extern const char *MPEG4HP41BDTransferSyntaxUID;
extern const char *MPEG4HP422DTransferSyntaxUID;
extern const char *MPEG4HP423DTransferSyntaxUID;
extern const char *MPEG4HP42STTransferSyntaxUID;
extern const char *RLELosslessTransferSyntaxUID;
extern const char *GEImplicitVRLEExceptBEPixelsTransferSyntaxUID;
extern const char *DeflatedExplicitVRLittleEndianTransferSyntaxUID;
extern const char *PixelMedBzip2ExplicitVRLittleEndianTransferSyntaxUID;
extern const char *PixelMedEncapsulatedRawLittleEndianTransferSyntaxUID;
extern const char *AlgotecCompressedTransferSyntaxUID;
extern const char *ALIWaveletTransferSyntaxUID;
extern const char *SectraCompressionTransferSyntaxUID;
extern const char *SectraCompressionLSTransferSyntaxUID;

#endif /* __Header_transynu__ */
