// Automatically generated from template - EDITS WILL BE LOST

// Generated by iodcomp.awk with options select iodcomps

#ifndef __Header_iodcomps__
#define __Header_iodcomps__

CompositeIOD *
selectCompositeIOD(AttributeList *list,const char *profile)
{
	(void)list;
	Assert(list);

CompositeIOD *iod=0;

	if (Condition_CRImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_CRImage(list);
	}
	else if (Condition_CTImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_CTImage(list);
	}
	else if (Condition_MRImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_MRImage(list);
	}
	else if (Condition_NMImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_NMImage(list);
	}
	else if (Condition_USImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_USImage(list);
	}
	else if (Condition_USMultiFrameImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_USMultiFrameImage(list);
	}
	else if (Condition_SCImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_SCImage(list);
	}
	else if (Condition_MultiframeSingleBitSCImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_MultiframeSingleBitSCImage(list);
	}
	else if (Condition_MultiframeGrayscaleByteSCImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_MultiframeGrayscaleByteSCImage(list);
	}
	else if (Condition_MultiframeGrayscaleWordSCImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_MultiframeGrayscaleWordSCImage(list);
	}
	else if (Condition_MultiframeTrueColorSCImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_MultiframeTrueColorSCImage(list);
	}
	else if (Condition_StandaloneOverlayInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_StandaloneOverlay(list);
	}
	else if (Condition_StandaloneCurveInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_StandaloneCurve(list);
	}
	else if (Condition_StandaloneModalityLUTInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_StandaloneModalityLUT(list);
	}
	else if (Condition_StandaloneVOILUTInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_StandaloneVOILUT(list);
	}
	else if (Condition_LabelMapOrSegmentationInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_Segmentation(list);
	}
	else if (Condition_SurfaceSegmentationInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_SurfaceSegmentation(list);
	}
	else if (Condition_SpatialRegistrationInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_SpatialRegistration(list);
	}
	else if (Condition_DeformableSpatialRegistrationInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_DeformableSpatialRegistration(list);
	}
	else if (Condition_SpatialFiducialsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_SpatialFiducials(list);
	}
	else if (Condition_EncapsulatedPDFInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EncapsulatedPDF(list);
	}
	else if (Condition_EncapsulatedCDAInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EncapsulatedCDA(list);
	}
	else if (Condition_EncapsulatedSTLInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EncapsulatedSTL(list);
	}
	else if (Condition_RealWorldValueMappingInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RealWorldValueMapping(list);
	}
	else if (Condition_IVOCTImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_IVOCTImage(list);
	}
	else if (Condition_ParametricMapInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_ParametricMap(list);
	}
	else if (Condition_MediaStorageDirectoryInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_BasicDirectory(list);
	}
	else if (Condition_MediaStorageDirectoryInstance(list,0,list) && profile && strcmp(profile,"Dental") == 0) {
		iod = new CompositeIOD_BasicDirectoryDental(list);
	}
	else if (Condition_XAImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_XAImage(list);
	}
	else if (Condition_XRFImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_XRFImage(list);
	}
	else if (Condition_EnhancedXAImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EnhancedXAImage(list);
	}
	else if (Condition_EnhancedXRFImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EnhancedXRFImage(list);
	}
	else if (Condition_XRay3DAngiographicImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_XRay3DAngiographicImage(list);
	}
	else if (Condition_XRay3DCraniofacialImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_XRay3DCraniofacialImage(list);
	}
	else if (Condition_PETImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_PETImage(list);
	}
	else if (Condition_EnhancedPETImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EnhancedPETImage(list);
	}
	else if (Condition_LegacyConvertedEnhancedPETImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_LegacyConvertedEnhancedPETImage(list);
	}
	else if (Condition_PrivatePixelMedLegacyConvertedEnhancedPETImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_PrivatePixelMedLegacyConvertedEnhancedPETImage(list);
	}
	else if (Condition_RTImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RTImage(list);
	}
	else if (Condition_RTDoseInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RTDose(list);
	}
	else if (Condition_RTStructureSetInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RTStructureSet(list);
	}
	else if (Condition_RTPlanInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RTPlan(list);
	}
	else if (Condition_RTBeamsTreatmentRecordInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RTBeamsTreatmentRecord(list);
	}
	else if (Condition_RTBrachyTreatmentRecordInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RTBrachyTreatmentRecord(list);
	}
	else if (Condition_RTTreatmentSummaryRecordInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RTTreatmentSummaryRecord(list);
	}
	else if (Condition_RTIonPlanInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RTIonPlan(list);
	}
	else if (Condition_RTIonBeamsTreatmentRecordInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RTIonBeamsTreatmentRecord(list);
	}
	else if (Condition_DXImageForProcessingInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_DXImageForProcessing(list);
	}
	else if (Condition_DXImageForPresentationInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_DXImageForPresentation(list);
	}
	else if (Condition_MammographyImageForProcessingInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_MammographyImageForProcessing(list);
	}
	else if (Condition_MammographyImageForPresentationInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_MammographyImageForPresentation(list);
	}
	else if (Condition_MammographyImageForProcessingInstance(list,0,list) && profile && strcmp(profile,"IHEMammo") == 0) {
		iod = new CompositeIOD_MammographyImageForProcessingIHEMammo(list);
	}
	else if (Condition_MammographyImageForProcessingInstance(list,0,list) && profile && strcmp(profile,"IHEMammoPartialViewOption") == 0) {
		iod = new CompositeIOD_MammographyImageForProcessingIHEMammoPartialViewOption(list);
	}
	else if (Condition_MammographyImageForPresentationInstance(list,0,list) && profile && strcmp(profile,"IHEMammo") == 0) {
		iod = new CompositeIOD_MammographyImageForPresentationIHEMammo(list);
	}
	else if (Condition_MammographyImageForPresentationInstance(list,0,list) && profile && strcmp(profile,"IHEMammoPartialViewOption") == 0) {
		iod = new CompositeIOD_MammographyImageForPresentationIHEMammoPartialViewOption(list);
	}
	else if (Condition_IntraoralImageForProcessingInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_IntraoralImageForProcessing(list);
	}
	else if (Condition_IntraoralImageForPresentationInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_IntraoralImageForPresentation(list);
	}
	else if (Condition_IntraoralImageForPresentationInstance(list,0,list) && profile && strcmp(profile,"Dental") == 0) {
		iod = new CompositeIOD_IntraoralImageForPresentationDentalMedia(list);
	}
	else if (Condition_DXImageForPresentationInstance(list,0,list) && profile && strcmp(profile,"Dental") == 0) {
		iod = new CompositeIOD_DXImageForPresentationDentalMedia(list);
	}
	else if (Condition_BreastTomosynthesisInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_BreastTomosynthesisImage(list);
	}
	else if (Condition_BreastTomosynthesisInstance(list,0,list) && profile && strcmp(profile,"IHEDBT") == 0) {
		iod = new CompositeIOD_BreastTomosynthesisImageIHEDBT(list);
	}
	else if (Condition_BreastProjectionXRayImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_BreastProjectionXRayImage(list);
	}
	else if (Condition_VisibleLightEndoscopicImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_VLEndoscopicImage(list);
	}
	else if (Condition_VisibleLightMicroscopicImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_VLMicroscopicImage(list);
	}
	else if (Condition_VisibleLightSlideCoordinatesMicroscopicImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_VLSlideCoordinatesMicroscopicImage(list);
	}
	else if (Condition_VisibleLightPhotographicImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_VLPhotographicImage(list);
	}
	else if (Condition_VideoEndoscopicImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_VideoEndoscopicImage(list);
	}
	else if (Condition_VideoMicroscopicImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_VideoMicroscopicImage(list);
	}
	else if (Condition_VideoPhotographicImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_VideoPhotographicImage(list);
	}
	else if (Condition_OphthalmicPhotography8BitImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_OphthalmicPhotography8BitImage(list);
	}
	else if (Condition_OphthalmicPhotography16BitImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_OphthalmicPhotography16BitImage(list);
	}
	else if (Condition_StereometricRelationshipInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_StereometricRelationship(list);
	}
	else if (Condition_OphthalmicTomographyImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_OphthalmicTomographyImage(list);
	}
	else if (Condition_OphthalmicOpticalCoherenceTomographyEnFaceImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_OphthalmicOpticalCoherenceTomographyEnFaceImage(list);
	}
	else if (Condition_OphthalmicOpticalCoherenceTomographyBscanVolumeAnalysisInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_OphthalmicOpticalCoherenceTomographyBscanVolumeAnalysis(list);
	}
	else if (Condition_VLWholeSlideMicroscopyImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_VLWholeSlideMicroscopyImage(list);
	}
	else if (Condition_VLWholeSlideMicroscopyImageInstance(list,0,list) && profile && strcmp(profile,"WG26SP2025") == 0) {
		iod = new CompositeIOD_VLWholeSlideMicroscopyImageWG26SP2025(list);
	}
	else if (Condition_LensometryMeasurementsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_LensometryMeasurements(list);
	}
	else if (Condition_AutorefractionMeasurementsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_AutorefractionMeasurements(list);
	}
	else if (Condition_KeratometryMeasurementsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_KeratometryMeasurements(list);
	}
	else if (Condition_SubjectiveRefractionMeasurementsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_SubjectiveRefractionMeasurements(list);
	}
	else if (Condition_VisualAcuityMeasurementsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_VisualAcuityMeasurements(list);
	}
	else if (Condition_OphthalmicAxialMeasurementsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_OphthalmicAxialMeasurements(list);
	}
	else if (Condition_IntraocularLensCalculationsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_IntraocularLensCalculations(list);
	}
	else if (Condition_OphthalmicVisualFieldStaticPerimetryMeasurementsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_OphthalmicVisualFieldStaticPerimetryMeasurements(list);
	}
	else if (Condition_DermoscopicPhotographyImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_DermoscopicPhotographyImage(list);
	}
	else if (Condition_MicroscopyBulkSimpleAnnotationsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_MicroscopyBulkSimpleAnnotations(list);
	}
	else if (Condition_MicroscopyBulkSimpleAnnotationsInstance(list,0,list) && profile && strcmp(profile,"WG26SP2025") == 0) {
		iod = new CompositeIOD_MicroscopyBulkSimpleAnnotationsWG26SP2025(list);
	}
	else if (Condition_BasicVoiceInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_BasicVoice(list);
	}
	else if (Condition_TwelveLeadECGInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_TwelveLeadECG(list);
	}
	else if (Condition_GeneralECGInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_GeneralECG(list);
	}
	else if (Condition_AmbulatoryECGInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_AmbulatoryECG(list);
	}
	else if (Condition_HemodynamicWaveformInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_HemodynamicWaveform(list);
	}
	else if (Condition_CardiacElectrophysiologyWaveformInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_CardiacElectrophysiologyWaveform(list);
	}
	else if (Condition_BasicTextSRStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_BasicTextSR(list);
	}
	else if (Condition_EnhancedSRStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EnhancedSR(list);
	}
	else if (Condition_ComprehensiveSRStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_ComprehensiveSR(list);
	}
	else if (Condition_Comprehensive3DSRStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_Comprehensive3DSR(list);
	}
	else if (Condition_KeyObjectSelectionDocumentStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_KeyObjectSelectionDocument(list);
	}
	else if (Condition_KeyObjectSelectionDocumentStorageInstance(list,0,list) && profile && strcmp(profile,"IHEXDSIManifest") == 0) {
		iod = new CompositeIOD_KeyObjectSelectionDocumentIHEXDSIManifest(list);
	}
	else if (Condition_MammographyCADSRStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_MammographyCADSR(list);
	}
	else if (Condition_ChestCADSRStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_ChestCADSR(list);
	}
	else if (Condition_ProcedureLogStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_ProcedureLog(list);
	}
	else if (Condition_XRayRadiationDoseSRStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_XRayRadiationDoseSR(list);
	}
	else if (Condition_XRayRadiationDoseSRStorageInstance(list,0,list) && profile && strcmp(profile,"IHEREM") == 0) {
		iod = new CompositeIOD_XRayRadiationDoseSRIHEREM(list);
	}
	else if (Condition_RadiopharmaceuticalRadiationDoseSRStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RadiopharmaceuticalRadiationDoseSR(list);
	}
	else if (Condition_SpectaclePrescriptionReportInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_SpectaclePrescriptionReport(list);
	}
	else if (Condition_AcquisitionContextSRStorageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_AcquisitionContextSR(list);
	}
	else if (Condition_GrayscaleSoftcopyPresentationStateInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_GrayscaleSoftcopyPresentationState(list);
	}
	else if (Condition_ColorSoftcopyPresentationStateInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_ColorSoftcopyPresentationState(list);
	}
	else if (Condition_PseudoColorSoftcopyPresentationStateInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_PseudoColorSoftcopyPresentationState(list);
	}
	else if (Condition_BlendingSoftcopyPresentationStateInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_BlendingSoftcopyPresentationState(list);
	}
	else if (Condition_AdvancedBlendingSoftcopyPresentationStateInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_AdvancedBlendingSoftcopyPresentationState(list);
	}
	else if (Condition_AdvancedBlendingSoftcopyPresentationStateInstance(list,0,list) && profile && strcmp(profile,"IDCVOIPaletteOpticalPath") == 0) {
		iod = new CompositeIOD_AdvancedBlendingSoftcopyPresentationStateIDCVOIPaletteOpticalPath(list);
	}
	else if (Condition_HangingProtocolInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_HangingProtocol(list);
	}
	else if (Condition_ColorPaletteInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_ColorPalette(list);
	}
	else if (Condition_BasicStructuredDisplayInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_BasicStructuredDisplay(list);
	}
	else if (Condition_EnhancedMRImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EnhancedMRImage(list);
	}
	else if (Condition_EnhancedMRColorImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EnhancedMRColorImage(list);
	}
	else if (Condition_MRSpectroscopyInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_MRSpectroscopy(list);
	}
	else if (Condition_RawDataInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_RawData(list);
	}
	else if (Condition_LegacyConvertedEnhancedMRImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_LegacyConvertedEnhancedMRImage(list);
	}
	else if (Condition_PrivatePixelMedLegacyConvertedEnhancedMRImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_PrivatePixelMedLegacyConvertedEnhancedMRImage(list);
	}
	else if (Condition_TractographyResultsInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_TractographyResults(list);
	}
	else if (Condition_EnhancedCTImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EnhancedCTImage(list);
	}
	else if (Condition_LegacyConvertedEnhancedCTImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_LegacyConvertedEnhancedCTImage(list);
	}
	else if (Condition_PrivatePixelMedLegacyConvertedEnhancedCTImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_PrivatePixelMedLegacyConvertedEnhancedCTImage(list);
	}
	else if (Condition_EnhancedUltrasoundVolumeInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_EnhancedUltrasoundVolume(list);
	}
	else if (Condition_EnhancedUltrasoundVolumeInstance(list,0,list) && profile && strcmp(profile,"QTUS") == 0) {
		iod = new CompositeIOD_EnhancedUltrasoundVolumeQTUS(list);
	}
	else if (Condition_PhotoacousticImageInstance(list,0,list) && profile == NULL) {
		iod = new CompositeIOD_PhotoacousticImage(list);
	}

	return iod;
}


#endif /* __Header_iodcomps__ */
