// Automatically generated from template - EDITS WILL BE LOST

// Generated by transyn.awk with options constant transync

#ifndef __Header_transync__
#define __Header_transync__

const char *ImplicitVRLittleEndianTransferSyntaxUID = "1.2.840.10008.1.2";
const char *DefaultTransferSyntaxUID = "1.2.840.10008.1.2";
const char *CommandTransferSyntaxUID = "1.2.840.10008.1.2";
const char *Papyrus3TransferSyntaxUID = "1.2.840.10008.1.20";
const char *ExplicitVRLittleEndianTransferSyntaxUID = "1.2.840.10008.1.2.1";
const char *MetaInformationTransferSyntaxUID = "1.2.840.10008.1.2.1";
const char *ExplicitVRBigEndianTransferSyntaxUID = "1.2.840.10008.1.2.2";
const char *JPEGProcess1TransferSyntaxUID = "1.2.840.10008.1.2.4.50";
const char *JPEGProcess2_4TransferSyntaxUID = "1.2.840.10008.1.2.4.51";
const char *JPEGProcess3_5TransferSyntaxUID = "1.2.840.10008.1.2.4.52";
const char *JPEGProcess6_8TransferSyntaxUID = "1.2.840.10008.1.2.4.53";
const char *JPEGProcess7_9TransferSyntaxUID = "1.2.840.10008.1.2.4.54";
const char *JPEGProcess10_12TransferSyntaxUID = "1.2.840.10008.1.2.4.55";
const char *JPEGProcess11_13TransferSyntaxUID = "1.2.840.10008.1.2.4.56";
const char *JPEGProcess14TransferSyntaxUID = "1.2.840.10008.1.2.4.57";
const char *JPEGProcess15TransferSyntaxUID = "1.2.840.10008.1.2.4.58";
const char *JPEGProcess16_18TransferSyntaxUID = "1.2.840.10008.1.2.4.59";
const char *JPEGProcess17_19TransferSyntaxUID = "1.2.840.10008.1.2.4.60";
const char *JPEGProcess20_22TransferSyntaxUID = "1.2.840.10008.1.2.4.61";
const char *JPEGProcess21_23TransferSyntaxUID = "1.2.840.10008.1.2.4.62";
const char *JPEGProcess24_26TransferSyntaxUID = "1.2.840.10008.1.2.4.63";
const char *JPEGProcess25_27TransferSyntaxUID = "1.2.840.10008.1.2.4.64";
const char *JPEGProcess28TransferSyntaxUID = "1.2.840.10008.1.2.4.65";
const char *JPEGProcess29TransferSyntaxUID = "1.2.840.10008.1.2.4.66";
const char *JPEGProcess14SV1TransferSyntaxUID = "1.2.840.10008.1.2.4.70";
const char *JPEGLSLosslessTransferSyntaxUID = "1.2.840.10008.1.2.4.80";
const char *JPEGLSNearLosslessTransferSyntaxUID = "1.2.840.10008.1.2.4.81";
const char *JPEG2000LosslessTransferSyntaxUID = "1.2.840.10008.1.2.4.90";
const char *JPEG2000TransferSyntaxUID = "1.2.840.10008.1.2.4.91";
const char *JPEGXLLosslessTransferSyntaxUID = "1.2.840.10008.1.2.4.110";
const char *JPEGXLRecompressionTransferSyntaxUID = "1.2.840.10008.1.2.4.111";
const char *JPEGXLTransferSyntaxUID = "1.2.840.10008.1.2.4.112";
const char *HTJ2KLosslessTransferSyntaxUID = "1.2.840.10008.1.2.4.201";
const char *HTJ2KLosslessRCPLTransferSyntaxUID = "1.2.840.10008.1.2.4.202";
const char *HTJ2KTransferSyntaxUID = "1.2.840.10008.1.2.4.203";
const char *MPEG2MPMLTransferSyntaxUID = "1.2.840.10008.1.2.4.100";
const char *MPEG2MPHLTransferSyntaxUID = "1.2.840.10008.1.2.4.101";
const char *MPEG4HP41TransferSyntaxUID = "1.2.840.10008.1.2.4.102";
const char *MPEG4HP41BDTransferSyntaxUID = "1.2.840.10008.1.2.4.103";
const char *MPEG4HP422DTransferSyntaxUID = "1.2.840.10008.1.2.4.104";
const char *MPEG4HP423DTransferSyntaxUID = "1.2.840.10008.1.2.4.105";
const char *MPEG4HP42STTransferSyntaxUID = "1.2.840.10008.1.2.4.106";
const char *RLELosslessTransferSyntaxUID = "1.2.840.10008.1.2.5";
const char *GEImplicitVRLEExceptBEPixelsTransferSyntaxUID = "1.2.840.113619.5.2";
const char *DeflatedExplicitVRLittleEndianTransferSyntaxUID = "1.2.840.10008.1.2.1.99";
const char *PixelMedBzip2ExplicitVRLittleEndianTransferSyntaxUID = "1.3.6.1.4.1.5962.300.1";
const char *PixelMedEncapsulatedRawLittleEndianTransferSyntaxUID = "1.3.6.1.4.1.5962.300.2";
const char *AlgotecCompressedTransferSyntaxUID = "1.2.840.113704.7.0.4.4";
const char *ALIWaveletTransferSyntaxUID = "1.2.840.113711.1.2.100.1";
const char *SectraCompressionTransferSyntaxUID = "1.2.752.24.3.7.6";
const char *SectraCompressionLSTransferSyntaxUID = "1.2.752.24.3.7.7";

#endif /* __Header_transync__ */
