// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=wholeheader
// 	 prefix=HIMR_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=HIMR_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=HIMR_HeaderClass
// 	 headerdicomclassprefix=HIMR_Header_BothClass
// 	 headerdumpclassprefix=HIMR_Header_BothClass
// 	 headerinstanceprefix=HIMR_HeaderInstance
// 	 methodnameprefix=HIMR_Method
// 	 methodconstructorargsprefix=HIMR_MethodConstructorArgs
// 	 headerclassparameters=

class HIMR_HeaderClass
{
public:
	HIMR_HeaderClass(istream *ist);

	HIMR_HeaderClass_IMGHDR *HIMR_HeaderInstance_IMGHDR;
};
