// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=headerpart
// 	 prefix=SGN_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=SGN_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=SGN_HeaderClass
// 	 headerdicomclassprefix=SGN_Header_BothClass
// 	 headerdumpclassprefix=SGN_Header_BothClass
// 	 headerinstanceprefix=SGN_HeaderInstance
// 	 methodnameprefix=SGN_Method
// 	 methodconstructorargsprefix=SGN_MethodConstructorArgs
// 	 headerclassparameters=

class SGN_HeaderClass_STUDYHDR {
public:
	SGN_HeaderClass_STUDYHDR(istream *ist,long offset)
		 { ReadProprietaryHeader(ist,offset,sizeof *this,(char *)this); }

	String<14> 	unknown4	; // at 0
	String<8> 	unknown5	; // at 14
	Int16_B 	unknown6	; // at 22
	String<32> 	unknown7	; // at 24
	Int16_B 	unknown8	; // at 56
	String<5> 	unknown9	; // at 58
	char 		reserved_1	[1]	;
	String<5> 	StudyNumber	; // at 64
	char 		reserved_2	[1]	;
	String<3> 	unknown11	; // at 70
	char 		reserved_3	[1]	;
	String<3> 	unknown12	; // at 74
	char 		reserved_4	[1]	;
	String<9> 	unknown13	; // at 78
	char 		reserved_5	[1]	;
	Int16_B 	StudyDateDay	; // at 88
	Int16_B 	StudyDateMonth	; // at 90
	Int16_B 	StudyDateYear	; // at 92
	String<8> 	unknown17	; // at 94
	Int16_B 	StudyTimeHour	; // at 102
	Int16_B 	StudyTimeMin	; // at 104
	Int16_B 	StudyTimeSec	; // at 106
	String<32> 	unknown21	; // at 108
	String<12> 	unknown22	; // at 140
	String<4> 	unknown23	; // at 152
	String<4> 	PatientAge	; // at 156
	String<1> 	unknown25	; // at 160
	char 		reserved_6	[1]	;
	Int32_B 	PatientWeightGrams	; // at 162
	String<32> 	unknown27	; // at 166
	String<32> 	unknown28	; // at 198
	String<32> 	unknown29	; // at 230
	String<60> 	unknown30	; // at 262
	String<120> 	unknown31	; // at 322
	Int32_B 	unknown32	; // at 442
	String<32> 	unknown33	; // at 446
	Int16_B 	unknown34	; // at 478
	String<12> 	unknown35	; // at 480
	char 		reserved_7	[530]	;
	Int16_B 	unknown36	; // at 1022
};

class SGN_HeaderClass_SERIESHDR {
public:
	SGN_HeaderClass_SERIESHDR(istream *ist,long offset)
		 { ReadProprietaryHeader(ist,offset,sizeof *this,(char *)this); }

	String<14> 	unknown39	; // at 0
	String<8> 	unknown40	; // at 14
	Int16_B 	unknown41	; // at 22
	String<32> 	unknown42	; // at 24
	Int16_B 	unknown43	; // at 56
	String<3> 	unknown44	; // at 58
	char 		reserved_8	[1]	;
	String<3> 	SeriesNumber	; // at 62
	char 		reserved_9	[1]	;
	String<3> 	unknown46	; // at 66
	char 		reserved_10	[1]	;
	String<3> 	unknown47	; // at 70
	char 		reserved_11	[1]	;
	String<9> 	unknown48	; // at 74
	char 		reserved_12	[1]	;
	Int16_B 	SeriesDateDay	; // at 84
	Int16_B 	SeriesDateMonth	; // at 86
	Int16_B 	SeriesDateYear	; // at 88
	String<8> 	unknown52	; // at 90
	Int16_B 	SeriesTimeHour	; // at 98
	Int16_B 	SeriesTimeMin	; // at 100
	Int16_B 	SeriesTimeSec	; // at 102
	String<120> 	unknown56	; // at 104
	Int16_B 	SeriesType	; // at 224
	Int16_B 	CoilType	; // at 226
	String<16> 	CoilName	; // at 228
	String<32> 	unknown60	; // at 244
	Int16_B 	PlaneType	; // at 276
	String<16> 	PlaneName	; // at 278
	Int16_B 	ImageMode	; // at 294
	Int16_B 	MagneticFieldStrengthGauss	; // at 296
	Int16_B 	PulseSequence	; // at 298
	Int16_B 	unknown66	; // at 300
	DG_Float_F 	FieldOfView	; // at 302
	DG_Float_F 	CenterRL	; // at 306
	DG_Float_F 	CenterAP	; // at 310
	DG_Float_F 	CenterSI	; // at 314
	Int16_B 	PatientOrientation	; // at 318
	Int16_B 	PatientPosition	; // at 320
	String<32> 	LongitudinalReference	; // at 322
	String<32> 	VerticalReference	; // at 354
	DG_Float_F 	VerticalLandmark	; // at 386
	DG_Float_F 	HorizontalLandmark	; // at 390
	DG_Float_F 	PhysicalTableLocation	; // at 394
	Int16_B 	ScanMatrixX	; // at 398
	Int16_B 	ScanMatrixY	; // at 400
	Int16_B 	ImageMatrix	; // at 402
	Int16_B 	unknown81	; // at 404
	Int16_B 	GatingType	; // at 406
	Int16_B 	PSMode	; // at 408
	String<12> 	unknown84	; // at 410
	Int32_B 	unknown85	; // at 422
	String<20> 	unknown86	; // at 426
	Int16_B 	SCoilType	; // at 446
	Int16_B 	SuppTech	; // at 448
	Int16_B 	Sat	; // at 450
	Int16_B 	SCIC	; // at 452
	Int16_B 	unknown91	; // at 454
	Int16_B 	unknown92	; // at 456
	Int16_B 	unknown93	; // at 458
	Int16_B 	unknown94	; // at 460
	Int16_B 	unknown95	; // at 462
	Int16_B 	unknown96	; // at 464
	Int16_B 	unknown97	; // at 466
	Int16_B 	unknown98	; // at 468
	Int16_B 	unknown99	; // at 470
	Int16_B 	VasMode	; // at 472
	Int16_B 	FlowAxis	; // at 474
	Int16_B 	unknown102	; // at 476
	Int16_B 	GatingType2	; // at 478
	char 		reserved_13	[542]	;
	Int16_B 	unknown104	; // at 1022
};

class SGN_HeaderClass_IMAGEHDR {
public:
	SGN_HeaderClass_IMAGEHDR(istream *ist,long offset)
		 { ReadProprietaryHeader(ist,offset,sizeof *this,(char *)this); }

	String<14> 	unknown107	; // at 0
	String<8> 	unknown108	; // at 14
	Int16_B 	unknown109	; // at 22
	String<32> 	unknown110	; // at 24
	Int16_B 	unknown111	; // at 56
	String<9> 	unknown112	; // at 58
	char 		reserved_14	[1]	;
	Int16_B 	ImageDateDay	; // at 68
	Int16_B 	ImageDateMonth	; // at 70
	Int16_B 	ImageDateYear	; // at 72
	String<8> 	unknown116	; // at 74
	Int16_B 	ImageTimeHour	; // at 82
	Int16_B 	ImageTimeMin	; // at 84
	Int16_B 	ImageTimeSec	; // at 86
	String<3> 	ImageNumber	; // at 88
	char 		reserved_15	[1]	;
	String<3> 	unknown121	; // at 92
	char 		reserved_16	[1]	;
	String<3> 	unknown122	; // at 96
	char 		reserved_17	[1]	;
	String<3> 	unknown123	; // at 100
	char 		reserved_18	[1]	;
	DG_Float_F 	LocationRMin	; // at 104
	DG_Float_F 	LocationRMax	; // at 108
	DG_Float_F 	LocationAMin	; // at 112
	DG_Float_F 	LocationAMax	; // at 116
	DG_Float_F 	LocationSMin	; // at 120
	DG_Float_F 	LocationSMax	; // at 124
	char 		reserved_19	[18]	;
	DG_Float_F 	SliceLocation	; // at 146
	DG_Float_F 	TablePosition	; // at 150
	DG_Float_F 	unknown132	; // at 154
	DG_Float_F 	unknown133	; // at 158
	Int16_B 	unknown134	; // at 162
	DG_Float_F 	RepetitionTimeUS	; // at 164
	DG_Float_F 	ScanTimeUS	; // at 168
	DG_Float_F 	EchoTimeUS	; // at 172
	DG_Float_F 	InversionTimeUS	; // at 176
	DG_Float_F 	unknown139	; // at 180
	DG_Float_F 	unknown140	; // at 184
	DG_Float_F 	unknown141	; // at 188
	DG_Float_F 	unknown142	; // at 192
	Int16_B 	NumberOfEchoes	; // at 196
	Int16_B 	unknown144	; // at 198
	Int16_B 	unknown145	; // at 200
	Int16_B 	unknown146	; // at 202
	Int16_B 	unknown147	; // at 204
	String<32> 	unknown148	; // at 206
	Int16_B 	unknown149	; // at 238
	Int16_B 	unknown150	; // at 240
	Int16_B 	unknown151	; // at 242
	Int16_B 	unknown152	; // at 244
	Int16_B 	unknown153	; // at 246
	Int16_B 	unknown154	; // at 248
	Int16_B 	unknown155	; // at 250
	String<9> 	unknown156	; // at 252
	char 		reserved_20	[1]	;
	String<9> 	unknown157	; // at 262
	char 		reserved_21	[1]	;
	Int16_B 	unknown158	; // at 272
	Int16_B 	unknown159	; // at 274
	Int16_B 	unknown160	; // at 276
	DG_Float_F 	PixelSize	; // at 278
	Int16_B 	unknown162	; // at 282
	Int16_B 	unknown163	; // at 284
	Int16_B 	DefaultWindow	; // at 286
	Int16_B 	DefaultLevel	; // at 288
	Int16_B 	unknown166	; // at 290
	DG_Float_F 	unknown167	; // at 292
	DG_Float_F 	unknown168	; // at 296
	DG_Float_F 	unknown169	; // at 300
	Int16_B 	unknown170	; // at 304
	Int16_B 	unknown171	; // at 306
	Int16_B 	unknown172	; // at 308
	DG_Float_F 	unknown173	; // at 310
	Int16_B 	unknown174	; // at 314
	Int16_B 	unknown175	; // at 316
	Int16_B 	unknown176	; // at 318
	Int32_B 	unknown177	; // at 320
	Int16_B 	unknown178	; // at 324
	Int16_B 	unknown179	; // at 326
	Int32_B 	unknown180	; // at 328
	Int16_B 	unknown181	; // at 332
	DG_Float_F 	unknown182	; // at 334
	String<12> 	unknown183	; // at 338
	Int16_B 	unknown184	; // at 350
	String<4> 	unknown185	; // at 352
	String<3> 	unknown186	; // at 356
	char 		reserved_22	[1]	;
	String<3> 	unknown187	; // at 360
	char 		reserved_23	[1]	;
	Int16_B 	unknown188	; // at 364
	char 		reserved_24	[20]	;
	String<3> 	unknown189	; // at 386
	char 		reserved_25	[1]	;
	String<3> 	unknown190	; // at 390
	char 		reserved_26	[1]	;
	DG_Float_F 	unknown191	; // at 394
	DG_Float_F 	unknown192	; // at 398
	DG_Float_F 	unknown193	; // at 402
	DG_Float_F 	unknown194	; // at 406
	DG_Float_F 	unknown195	; // at 410
	DG_Float_F 	unknown196	; // at 414
	DG_Float_F 	TLHC_R	; // at 418
	DG_Float_F 	TLHC_A	; // at 422
	DG_Float_F 	TLHC_S	; // at 426
	DG_Float_F 	TRHC_R	; // at 430
	DG_Float_F 	TRHC_A	; // at 434
	DG_Float_F 	TRHC_S	; // at 438
	DG_Float_F 	BLHC_R	; // at 442
	DG_Float_F 	BLHC_A	; // at 446
	DG_Float_F 	BLHC_S	; // at 450
	Int16_B 	unknown206	; // at 454
	Int16_B 	unknown207	; // at 456
	Int16_B 	unknown208	; // at 458
	DG_Float_F 	unknown209	; // at 460
	Int16_B 	unknown210	; // at 464
	Int16_B 	unknown211	; // at 466
	DG_Float_F 	unknown212	; // at 468
	Int16_B 	unknown213	; // at 472
	Int16_B 	unknown214	; // at 474
	char 		reserved_27	[2]	;
	Int16_B 	unknown215	; // at 478
	char 		reserved_28	[2]	;
	Int16_B 	unknown216	; // at 482
	char 		reserved_29	[2]	;
	Int16_B 	unknown217	; // at 486
	char 		reserved_30	[2]	;
	Int16_B 	unknown218	; // at 490
	char 		reserved_31	[2]	;
	Int16_B 	unknown219	; // at 494
	char 		reserved_32	[2]	;
	Int16_B 	unknown220	; // at 498
	char 		reserved_33	[2]	;
	Int16_B 	unknown221	; // at 502
	char 		reserved_34	[2]	;
	Int16_B 	unknown222	; // at 506
	char 		reserved_35	[2]	;
	Int16_B 	unknown223	; // at 510
	char 		reserved_36	[2]	;
	Int16_B 	unknown224	; // at 514
	Int16_B 	ContrastUsed	; // at 516
	String<10> 	unknown226	; // at 518
	DG_Float_F 	unknown227	; // at 528
	Int16_B 	unknown228	; // at 532
	Int16_B 	unknown229	; // at 534
	Int32_B 	TransmitFreq	; // at 536
	Int32_B 	unknown231	; // at 540
	Int32_B 	unknown232	; // at 544
	Int32_B 	unknown233	; // at 548
	Int32_B 	unknown234	; // at 552
	Int32_B 	unknown235	; // at 556
	Int16_B 	unknown236	; // at 560
	Int16_B 	PFSwapped	; // at 562
	Int16_B 	unknown238	; // at 564
	Int16_B 	unknown239	; // at 566
	Int16_B 	VariableBandwidth	; // at 568
	Int16_B 	unknown241	; // at 570
	Int16_B 	unknown242	; // at 572
	Int16_B 	unknown243	; // at 574
	Int16_B 	unknown244	; // at 576
	Int16_B 	unknown245	; // at 578
	Int16_B 	VascCollapse	; // at 580
	Int16_B 	unknown247	; // at 582
	Int16_B 	unknown248	; // at 584
	DG_Float_F 	unknown249	; // at 586
	Int16_B 	unknown250	; // at 590
	Int16_B 	FracEcho	; // at 592
	Int32_B 	EchoTrainLength	; // at 594
	Int16_B 	unknown253	; // at 598
	Int16_B 	unknown254	; // at 600
	Int16_B 	unknown255	; // at 602
	Int16_B 	unknown256	; // at 604
	DG_Float_F 	unknown257	; // at 606
	char 		reserved_37	[412]	;
	Int16_B 	unknown258	; // at 1022
};

