// Automatically generated from template - EDITS WILL BE LOST
//
// Generated by convert.awk with options or defaults ...
//
// 	 role=constructheader
// 	 prefix=SGN_
// 	 dicomfunctionname=ToDicom_Template
// 	 dumpcommonfunctionname=DumpCommon
// 	 dumpselectedimagefunctionname=DumpSelectedImage
// 	 headeroffsetprefix=SGN_Offset
// 	 headeroffsetsuffix=ptr
// 	 headerclassprefix=SGN_HeaderClass
// 	 headerdicomclassprefix=SGN_Header_BothClass
// 	 headerdumpclassprefix=SGN_Header_BothClass
// 	 headerinstanceprefix=SGN_HeaderInstance
// 	 methodnameprefix=SGN_Method
// 	 methodconstructorargsprefix=SGN_MethodConstructorArgs
// 	 headerclassparameters=

SGN_HeaderClass::SGN_HeaderClass(istream *ist)
{
	SGN_HeaderInstance_STUDYHDR = 0;
	SGN_HeaderInstance_STUDYHDR = new
		SGN_HeaderClass_STUDYHDR(ist,SGN_Offset_STUDYHDR_ptr);

	SGN_HeaderInstance_SERIESHDR = 0;
	SGN_HeaderInstance_SERIESHDR = new
		SGN_HeaderClass_SERIESHDR(ist,SGN_Offset_SERIESHDR_ptr);

	SGN_HeaderInstance_IMAGEHDR = 0;
	SGN_HeaderInstance_IMAGEHDR = new
		SGN_HeaderClass_IMAGEHDR(ist,SGN_Offset_IMAGEHDR_ptr);

}

